<select
  name="menu-from"
  class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required my-select select2-hidden-accessible"
  aria-required="true"
  aria-invalid="false"
  data-select2-id="select2-data-1-lrou"
  tabindex="-1"
  aria-hidden="true"
>
  <option value="" data-select2-id="select2-data-3-hh07">
    ---
  </option>
  <option value="">Aalborg - Denmark ( AAL )</option>
  <option value="">Aalesund - Norway ( AES )</option>
  <option value="">Aarhus - Denmark ( AAR )</option>
  <option value="">Abbotsford, BC - Canada ( YXX )</option>
  <option value="">Abbotsford, BCВ - CanadaВ ( YXX )</option>
  <option value="">AberdeenВ - Scotland ( ABZ )</option>
  <option value="">Aberdeen, SDВ - United States ( ABR )</option>
  <option value="">Abidjan - Ivory Coast ( ABJ )</option>
  <option value="">Abilene, TXВ - United States ( ABI )</option>
  <option value="">Abu Dhabi - United Arab Emirates ( AUH )</option>
  <option value="">Abuja - Nigeria ( ABV )</option>
  <option value="">Acapulco - Mexico ( ACA )</option>
  <option value="">Accra - Ghana ( ACC )</option>
  <option value="">Adana - Turkey ( ADA )</option>
  <option value="">Addis Ababa - Ethiopia ( ADD )</option>
  <option value="">Adelaide, S.A. - Australia ( ADL )</option>
  <option value="">Aden - Yemen ( ADE )</option>
  <option value="">Adiyaman - Turkey ( ADF )</option>
  <option value="">Agadir - Morocco ( AGA )</option>
  <option value="">Agana - Guam ( GUM )</option>
  <option value="">Aguadilla - Puerto Rico ( BQN )</option>
  <option value="">Aguascalientes - Mexico ( AGU )</option>
  <option value="">Ahe - French Polynesia ( AHE )</option>
  <option value="">Ahmedabad - India ( AMD )</option>
  <option value="">Ajaccio, Corsica - France ( AJA )</option>
  <option value="">Akita - Japan ( AXT )</option>
  <option value="">Anchorage, Alaska - USAB ( ANC )</option>
  <option value="">Akron, OHВ - United States ( CAK )</option>
  <option value="">Alamosa, COВ - United States ( ALS )</option>
  <option value="">Albany, GAВ - United States ( ABY )</option>
  <option value="">Albany, NYВ - United States ( ALB )</option>
  <option value="">Albenga - Italy ( ALL )</option>
  <option value="">Albuquerque, NMВ - United States ( ABQ )</option>
  <option value="">Albury, N.S.W. - Australia ( ABX )</option>
  <option value="">Alexandria - Egypt ( ALY )</option>
  <option value="">Alexandria - Egypt ( HBE )</option>
  <option value="">Alexandria, LAВ - United States ( AEX )</option>
  <option value="">Alexandroupolis - Greece ( AXD )</option>
  <option value="">Alghero, Sardinia - Italy ( AHO )</option>
  <option value="">Algiers - Algeria ( ALG )</option>
  <option value="">Alicante - Spain ( ALC )</option>
  <option value="">Alice Springs, N.T. - Australia ( ASP )</option>
  <option value="">Alice Town, North Bimini Island - Bahamas ( NSB )</option>
  <option value="">Allentown, PAВ - United States ( ABE )</option>
  <option value="">Alliance, NEВ - United States ( AIA )</option>
  <option value="">Almaty - Kazakhstan ( ALA )</option>
  <option value="">Almeria - Spain ( LEI )</option>
  <option value="">Alor Setar - Malaysia ( AOR )</option>
  <option value="">Alpena, MIВ - United States ( APN )</option>
  <option value="">Alta - Norway ( ALF )</option>
  <option value="">Altenrhein - Switzerland ( ACH )</option>
  <option value="">Altoona, PAВ - United States ( AOO )</option>
  <option value="">Amarillo, TXВ - United States ( AMA )</option>
  <option value="">Amman - Jordan ( AMM )</option>
  <option value="">Amsterdam - Netherlands ( AMS )</option>
  <option value="">Anahim Lake, BC - Canada ( YAA )</option>
  <option value="">Anahim Lake, BCВ - CanadaВ ( YAA )</option>
  <option value="">Anchorage, AKВ - United States ( ANC )</option>
  <option value="">Ancona - Italy ( AOI )</option>
  <option value="">Town - Bahamas ( ASD )</option>
  <option value="">Angeles City - Philippines ( CRK )</option>
  <option value="">Angra do Heroismo, Terceira Island - Azores ( TER )</option>
  <option value="">Ankara - Turkey ( ESB )</option>
  <option value="">Annaba - Algeria ( AAE )</option>
  <option value="">Annecy - France ( NCY )</option>
  <option value="">Antalya - Turkey ( AYT )</option>
  <option value="">Antananarivo - Madagascar ( TNR )</option>
  <option value="">Antofagasta - Chile ( ANF )</option>
  <option value="">Antwerp - Belgium ( ANR )</option>
  <option value="">Aomori - Japan ( AOJ )</option>
  <option value="">Aosta - Italy ( AOT )</option>
  <option value="">Appleton, WIВ - United States ( ATW )</option>
  <option value="">Ardabil - Iran ( ADU )</option>
  <option value="">Arequipa - Peru ( AQP )</option>
  <option value="">Argostoli, Kefalonia Island - Greece ( EFL )</option>
  <option value="">Arica - Chile ( ARI )</option>
  <option value="">Arkhangelsk - Russia ( ARH )</option>
  <option value="">Armidale, N.S.W. - Australia ( ARM )</option>
  <option value="">Arrecife, Lanzarote Island - Canary Islands ( ACE )</option>
  <option value="">Arusha - Tanzania ( ARK )</option>
  <option value="">Kilimanjaro - Tanzania ( JRO )</option>
  <option value="">Arviat, NWT - Canada ( YEK )</option>
  <option value="">Arviat, NWT - CanadaВ ( YEK )</option>
  <option value="">Arvidsjaur - Sweden ( AJR )</option>
  <option value="">Asheville, NCВ - United States ( AVL )</option>
  <option value="">Asmara - Eritrea ( ASM )</option>
  <option value="">Aspen, COВ - United States ( ASE )</option>
  <option value="">Astana - Kazakhstan ( TSE )</option>
  <option value="">Asuncion - Paraguay ( ASU )</option>
  <option value="">Aswan - Egypt ( ASW )</option>
  <option value="">Athens - Greece ( ATH )</option>
  <option value="">Athens, GAВ - United States ( AHN )</option>
  <option value="">Atlanta, GAВ - United States ( ATL )</option>
  <option value="">Atlantic City, NJВ - United States ( ACY )</option>
  <option value="">Auckland - New Zealand ( AKL )</option>
  <option value="">Augusta, GAВ - United States ( AGS )</option>
  <option value="">Augusta, MEВ - United States ( AUG )</option>
  <option value="">Austin, TXВ - United States ( AUS )</option>
  <option value="">Avarua, Rarotonga Island - Cook Islands ( RAR )</option>
  <option value="">Ayers Rock, N.T. - Australia ( AYQ )</option>
  <option value="">Bacolod - Philippines ( BCD )</option>
  <option value="">Badajoz - Spain ( BJZ )</option>
  <option value="">Baghdad - Iraq ( SDA )</option>
  <option value="">Bagotville, PQ - Canada ( YBG )</option>
  <option value="">Bagotville, PQВ - CanadaВ ( YBG )</option>
  <option value="">Baie-Comeau, PQ - Canada ( YBC )</option>
  <option value="">Baie-Comeau, PQВ - CanadaВ ( YBC )</option>
  <option value="">Bakersfield, CAВ - United States ( BFL )</option>
  <option value="">Baku - Azerbaijan ( BAK )</option>
  <option value="">Baku - Azerbaijan ( GYD )</option>
  <option value="">Balaton - Hungary ( SOB )</option>
  <option value="">Balephuil - Scotland ( TRE )</option>
  <option value="">Balikpapan, Kalimantan - Indonesia ( BPN )</option>
  <option value="">Ballina, N.S.W. - Australia ( BNK )</option>
  <option value="">Balmaceda - Chile ( BBA )</option>
  <option value="">Baltimore, MDВ - United States ( BWI )</option>
  <option value="">Ban Me Thuot - Vietnam ( BMV )</option>
  <option value="">Bandar Seri Begawan - Brunei ( BWN )</option>
  <option value="">Bangalore - India ( BLR )</option>
  <option value="">Bangda - China ( BPX )</option>
  <option value="">Bangkok - Thailand ( BKK )</option>
  <option value="">Bangor, MEВ - United States ( BGR )</option>
  <option value="">Bangui - Central African Republic ( BGF )</option>
  <option value="">Banjul - Gambia ( BJL )</option>
  <option value="">Bar Harbor, MEВ - United States ( BHB )</option>
  <option value="">Barcelona - Spain ( BCN )</option>
  <option value="">Bardufoss - Norway ( BDU )</option>
  <option value="">Bari - Italy ( BRI )</option>
  <option value="">Barisal - Bangladesh ( BZL )</option>
  <option value="">Barranquilla - Colombia ( BAQ )</option>
  <option value="">Barrow, AK - United States ( BRW )</option>
  <option value="">Basel - Switzerland ( BSL )</option>
  <option value="">Basseterre - St. Kitts ( SKB )</option>
  <option value="">Bastia, Corsica - France ( BIA )</option>
  <option value="">Bathurst, N.S.W. - Australia ( BHS )</option>
  <option value="">Baton Rouge, LAВ - United States ( BTR )</option>
  <option value="">Bauru - Brazil ( BAU )</option>
  <option value="">Beaumont, TXВ - United States ( BPT )</option>
  <option value="">Beauvais - France ( BVA )</option>
  <option value="">Beckley, WVВ - United States ( BKW )</option>
  <option value="">Bedford, MAВ - United States ( BED )</option>
  <option value="">
    Beef Island, Tortola - British Virgin Islands ( EIS )
  </option>
  <option value="">Beijing - China ( BJS )</option>
  <option value="">Beirut - Lebanon ( BEY )</option>
  <option value="">Belem - Brazil ( BEL )</option>
  <option value="">Belfast - Northern Ireland ( BFS )</option>
  <option value="">Belfast - Northern Ireland ( BHD )</option>
  <option value="">Belgrade - Serbia and Montenegro ( BEG )</option>
  <option value="">Belize City - Belize ( BZE )</option>
  <option value="">Bellingham, WAВ - United States ( BLI )</option>
  <option value="">Belo Horizonte - Brazil ( CNF )</option>
  <option value="">Bemidji, MNВ - United States ( BJI )</option>
  <option value="">Benbecula - Scotland ( BEB )</option>
  <option value="">Benguela - Angola ( BUG )</option>
  <option value="">Bergen - Norway ( BGO )</option>
  <option value="">Berlin - Germany ( BER - All Airports )</option>
  <option value="">Berlin - Germany ( SXF )</option>
  <option value="">Berlin - Germany ( THF )</option>
  <option value="">Berlin - Germany ( TXL )</option>
  <option value="">Berne - Switzerland ( BRN )</option>
  <option value="">Bethel, AKВ - United States ( BET )</option>
  <option value="">Bettles, AKВ - United States ( BTT )</option>
  <option value="">Biak, Papua - Indonesia ( BIK )</option>
  <option value="">Biarritz - France ( BIQ )</option>
  <option value="">Bilbao - Spain ( BIO )</option>
  <option value="">Billings, MTВ - United States ( BIL )</option>
  <option value="">Billund - Denmark ( BLL )</option>
  <option value="">Binghamton, NYВ - United States ( BGM )</option>
  <option value="">Bintulu, Sarawak - Malaysia ( BTU )</option>
  <option value="">Birmingham - England ( BHX )</option>
  <option value="">Birmingham, ALВ - United States ( BHM )</option>
  <option value="">Bishkek - Kyrgyzstan ( FRU )</option>
  <option value="">Bismarck, NDВ - United States ( BIS )</option>
  <option value="">Bissau - Guinea-Bissau ( OXB )</option>
  <option value="">Blantyre - Malawi ( BLZ )</option>
  <option value="">Blenheim - New Zealand ( BHE )</option>
  <option value="">Bloemfontein - South Africa ( BFN )</option>
  <option value="">Bloomington, ILВ - United States ( BMI )</option>
  <option value="">Bloomington, INВ - United States ( BMG )</option>
  <option value="">Bluefield, WVВ - United States ( BLF )</option>
  <option value="">Bodo - Norway ( BOO )</option>
  <option value="">Bogota - Colombia ( BOG )</option>
  <option value="">Boise, IDВ - United States ( BOI )</option>
  <option value="">Bologna - Italy ( BLQ )</option>
  <option value="">Bolzano - Italy ( BZO )</option>
  <option value="">Bordeaux - France ( BOD )</option>
  <option value="">Borlange - Sweden ( BLE )</option>
  <option value="">Boston, MAВ - United States ( BOS )</option>
  <option value="">Bozeman, MTВ - United States ( BZN )</option>
  <option value="">Brasilia - Brazil ( BSB )</option>
  <option value="">Bratislava - Slovakia ( BTS )</option>
  <option value="">Brazzaville - Congo ( BZV )</option>
  <option value="">Bremen - Germany ( BRE )</option>
  <option value="">Brest - France ( BES )</option>
  <option value="">Bridgetown - Barbados ( BGI )</option>
  <option value="">Brindisi - Italy ( BDS )</option>
  <option value="">Brisbane, Qld. - Australia ( BNE )</option>
  <option value="">Bristol - England ( BRS )</option>
  <option value="">Broken Hill, N.S.W. - Australia ( BHQ )</option>
  <option value="">Brookings, SDВ - United States ( BKX )</option>
  <option value="">Broome, W.A. - Australia ( BME )</option>
  <option value="">Brownsville, TXВ - United States ( BRO )</option>
  <option value="">Brunswick, GAВ - United States ( BQK )</option>
  <option value="">Brussels - Belgium ( BRU )</option>
  <option value="">Bucharest - Romania ( OTP )</option>
  <option value="">Budapest - Hungary ( BUD )</option>
  <option value="">Buenos Aires - Argentina ( EZE )</option>
  <option value="">Buffalo, NYВ - United States ( BUF )</option>
  <option value="">Bujumbura - Burundi ( BJM )</option>
  <option value="">Bulawayo - Zimbabwe ( BUQ )</option>
  <option value="">Bundaberg, Qld. - Australia ( BDB )</option>
  <option value="">Burbank, CAВ - United States ( BUR )</option>
  <option value="">Buri Ram - Thailand ( BFV )</option>
  <option value="">Burlington, IAВ - United States ( BRL )</option>
  <option value="">Burlington, MAВ - United States ( BBF )</option>
  <option value="">Burlington, VTВ - United States ( BTV )</option>
  <option value="">Busan, Korea - Republic of ( PUS )</option>
  <option value="">Butte, MTВ - United States ( BTM )</option>
  <option value="">Butuan - Philippines ( BXU )</option>
  <option value="">Bydgoszcz - Poland ( BZG )</option>
  <option value="">Caen - France ( CFR )</option>
  <option value="">Cagayan de Oro - Philippines ( CGY )</option>
  <option value="">Cagliari, Sardinia - Italy ( CAG )</option>
  <option value="">Cairns, Qld. - Australia ( CNS )</option>
  <option value="">Cairo - Egypt ( CAI )</option>
  <option value="">Kolkata - India ( CCU )</option>
  <option value="">Cotonou - Benin ( COO )</option>
  <option value="">Calgary, AB - Canada ( YYC )</option>
  <option value="">Calgary, ABВ - CanadaВ ( YYC )</option>
  <option value="">Cali - Colombia ( CLO )</option>
  <option value="">Calvi, Corsica - France ( CLY )</option>
  <option value="">Campbell River, BC - Canada ( YBL )</option>
  <option value="">Campbell River, BCВ - CanadaВ ( YBL )</option>
  <option value="">Campbeltown - Scotland ( CAL )</option>
  <option value="">Campeche - Mexico ( CPE )</option>
  <option value="">Canberra, A.C.T. - Australia ( CBR )</option>
  <option value="">Cancun - Mexico ( CUN )</option>
  <option value="">Cap-aux-Meules,В - CanadaВ ( YGR )</option>
  <option value="">
    Cap-aux-Meules, Magdalens Islands, PQ - Canada ( YGR )
  </option>
  <option value="">Cape Girardeau, MOВ - United States ( CGI )</option>
  <option value="">Cape Town - South Africa ( CPT )</option>
  <option value="">Caracas - Venezuela ( CCS )</option>
  <option value="">Cardiff - Wales ( CWL )</option>
  <option value="">Carlsbad, CAВ - United States ( CLD )</option>
  <option value="">Carlsbad, NMВ - United States ( CNM )</option>
  <option value="">Cartagena - Colombia ( CTG )</option>
  <option value="">Casablanca - Morocco ( CMN )</option>
  <option value="">Casper, WYВ - United States ( CPR )</option>
  <option value="">Castlegar, BC - Canada ( YCG )</option>
  <option value="">Castlegar, BCВ - CanadaВ ( YCG )</option>
  <option value="">Castries - St. Lucia ( SLU )</option>
  <option value="">Catania, Sicily - Italy ( CTA )</option>
  <option value="">Cayenne - French Guiana ( CAY )</option>
  <option value="">Cayman Brac - Cayman Islands ( CYB )</option>
  <option value="">Cebu - Philippines ( CEB )</option>
  <option value="">Cedar Rapids, IAВ - United States ( CID )</option>
  <option value="">Ceduna, S.A. - Australia ( CED )</option>
  <option value="">Champaign, ILВ - United States ( CMI )</option>
  <option value="">Changchun - China ( CGQ )</option>
  <option value="">Changsha - China ( CSX )</option>
  <option value="">Chania, Crete - Greece ( CHQ )</option>
  <option value="">Charleston, SCВ - United States ( CHS )</option>
  <option value="">Charleston, WVВ - United States ( CRW )</option>
  <option value="">Charleville, Qld. - Australia ( CTL )</option>
  <option value="">
    Charlotte Amalie, St. Thomas - U.S. Virgin Islands ( STT )
  </option>
  <option value="">Charlotte, NCВ - United States ( CLT )</option>
  <option value="">Charlottesville, VAВ - United States ( CHO )</option>
  <option value="">Charlottetown, PEI - Canada ( YYG )</option>
  <option value="">Charlottetown, PEIВ - CanadaВ ( YYG )</option>
  <option value="">Chattanooga, TNВ - United States ( CHA )</option>
  <option value="">Chengdu - China ( CTU )</option>
  <option value="">Chennai (Madras) - India ( MAA )</option>
  <option value="">Pune - India ( PNQ )</option>
  <option value="">Chetumal - Mexico ( CTM )</option>
  <option value="">Cheyenne, WYВ - United States ( CYS )</option>
  <option value="">Chiang Mai - Thailand ( CNX )</option>
  <option value="">Chiang Rai - Thailand ( CEI )</option>
  <option value="">Chibougamau, PQ - Canada ( YMT )</option>
  <option value="">Chibougamau, PQВ - CanadaВ ( YMT )</option>
  <option value="">Chicago, ILВ - United States ( CHIВ - AllВ )</option>
  <option value="">Chicago, ILВ - United States ( MDW )</option>
  <option value="">Chicago, ILВ - United States ( ORD )</option>
  <option value="">Chico, CAВ - United States ( CIC )</option>
  <option value="">Chihuahua - Mexico ( CUU )</option>
  <option value="">Chios - Greece ( JKH )</option>
  <option value="">Chisinau - Moldova ( KIV )</option>
  <option value="">Chongqing - China ( CKG )</option>
  <option value="">Christchurch - New Zealand ( CHC )</option>
  <option value="">
    Christiansted, St. Croix - U.S. Virgin Islands ( STX )
  </option>
  <option value="">Churchill, MB - Canada ( YYQ )</option>
  <option value="">Churchill, MBВ - CanadaВ ( YYQ )</option>
  <option value="">Cincinnati, OHВ - United States ( CVG )</option>
  <option value="">Ciudad Bolivar - Venezuela ( CBL )</option>
  <option value="">Ciudad Del Carmen - Mexico ( CME )</option>
  <option value="">Ciudad del Este - Paraguay ( AGT )</option>
  <option value="">Ciudad Juarez - Mexico ( CJS )</option>
  <option value="">Ciudad Obregon - Mexico ( CEN )</option>
  <option value="">Ciudad Victoria - Mexico ( CVM )</option>
  <option value="">Clarksburg, WVВ - United States ( CKB )</option>
  <option value="">Clermont-Ferrand - France ( CFE )</option>
  <option value="">Cleveland, OHВ - United States ( CLE )</option>
  <option value="">Clovis, NMВ - United States ( CVN )</option>
  <option value="">Cockburn Town, San Salvador Island - Bahamas ( ZSA )</option>
  <option value="">Cody, WYВ - United States ( COD )</option>
  <option value="">Coffs Harbour, N.S.W. - Australia ( CFS )</option>
  <option value="">Colima - Mexico ( CLQ )</option>
  <option value="">College Station, TXВ - United States ( CLL )</option>
  <option value="">Cologne - Germany ( CGN )</option>
  <option value="">Colombo - Sri Lanka ( CMB )</option>
  <option value="">Colorado Springs, COВ - United States ( COS )</option>
  <option value="">Columbia, MOВ - United States ( COU )</option>
  <option value="">Columbia, SCВ - United States ( CAE )</option>
  <option value="">Columbus, GAВ - United States ( CSG )</option>
  <option value="">Columbus, INВ - United States ( CLU )</option>
  <option value="">Columbus, MSВ - United States ( GTR )</option>
  <option value="">Columbus, NEВ - United States ( OLU )</option>
  <option value="">Columbus, OHВ - United States ( CMH )</option>
  <option value="">Conakry - Guinea ( CKY )</option>
  <option value="">Concepcion - Chile ( CCP )</option>
  <option value="">Connaught - Ireland ( NOC )</option>
  <option value="">Coober Pedy, S.A. - Australia ( CPD )</option>
  <option value="">Copenhagen - Denmark ( CPH )</option>
  <option value="">Copiapo - Chile ( CPO )</option>
  <option value="">Cordoba - Argentina ( COR )</option>
  <option value="">Cordova, AKВ - United States ( CDV )</option>
  <option value="">Cork - Ireland ( ORK )</option>
  <option value="">Corpus Christi, TXВ - United States ( CRP )</option>
  <option value="">Cotabato - Philippines ( CBO )</option>
  <option value="">Cozumel - Mexico ( CZM )</option>
  <option value="">Cranbrook, BC - Canada ( YXC )</option>
  <option value="">Cranbrook, BCВ - CanadaВ ( YXC )</option>
  <option value="">Crotone - Italy ( CRV )</option>
  <option value="">Cubi Point Nas - Philippines ( NCP )</option>
  <option value="">Culiacan - Mexico ( CUL )</option>
  <option value="">Curitiba - Brazil ( CWB )</option>
  <option value="">Cusco - Peru ( CUZ )</option>
  <option value="">Da Nang - Vietnam ( DAD )</option>
  <option value="">Dakar - Senegal ( DKR )</option>
  <option value="">Dalaman - Turkey ( DLM )</option>
  <option value="">Dali City - China ( DLU )</option>
  <option value="">Dalian - China ( DLC )</option>
  <option value="">Dallas, TXВ - United States ( DAL )</option>
  <option value="">Dallas, TXВ - United States ( DFW )</option>
  <option value="">Damascus - Syria ( DAM )</option>
  <option value="">Dangriga - Belize ( DGA )</option>
  <option value="">Dar es Salaam - Tanzania ( DAR )</option>
  <option value="">Darwin, N.T. - Australia ( DRW )</option>
  <option value="">Davao - Philippines ( DVO )</option>
  <option value="">Dawadmi - Saudi Arabia ( DWD )</option>
  <option value="">Dayong - China ( DYG )</option>
  <option value="">Dayton, OHВ - United States ( DAY )</option>
  <option value="">Daytona Beach, FLВ - United States ( DAB )</option>
  <option value="">Deadmans Cay, Long Island - Bahamas ( LGI )</option>
  <option value="">Deboyne - Papua-New Guinea ( DOY )</option>
  <option value="">Decatur, ILВ - United States ( DEC )</option>
  <option value="">Deer Lake, NF - Canada ( YDF )</option>
  <option value="">Deer Lake, NFВ - CanadaВ ( YDF )</option>
  <option value="">Delhi - India ( DEL )</option>
  <option value="">Denpasar, Bali - Indonesia ( DPS )</option>
  <option value="">Denver, COВ - United States ( DEN )</option>
  <option value="">Des Moines, IAВ - United States ( DSM )</option>
  <option value="">Detroit, MIВ - United States ( DTTВ - AllВ )</option>
  <option value="">Detroit, MIВ - United States ( DTW )</option>
  <option value="">Devils Lake, NDВ - United States ( DVL )</option>
  <option value="">Devonport, Tas. - Australia ( DPO )</option>
  <option value="">Dhahran - Saudi Arabia ( DHA )</option>
  <option value="">Dammam - Saudi Arabia ( DMM )</option>
  <option value="">Dhaka - Bangladesh ( DAC )</option>
  <option value="">Dickinson, NDВ - United States ( DIK )</option>
  <option value="">Dien-Bien-Phu - Vietnam ( DIN )</option>
  <option value="">Dillingham, AKВ - United States ( DLG )</option>
  <option value="">Dipolog - Philippines ( DPL )</option>
  <option value="">Djibouti - Djibouti ( JIB )</option>
  <option value="">Dnepropetrovsk - Ukraine ( DNK )</option>
  <option value="">Dodge City, KSВ - United States ( DDC )</option>
  <option value="">Doha - Qatar ( DOH )</option>
  <option value="">Doncaster - England ( DSA )</option>
  <option value="">Donetsk - Ukraine ( DOK )</option>
  <option value="">Dortmund - Germany ( DTM )</option>
  <option value="">Dothan, ALВ - United States ( DHN )</option>
  <option value="">Douala - Cameroon ( DLA )</option>
  <option value="">Dresden - Germany ( DRS )</option>
  <option value="">Dryden, ON - Canada ( YHD )</option>
  <option value="">Dryden, ONВ - CanadaВ ( YHD )</option>
  <option value="">Du Bois, PAВ - United States ( DUJ )</option>
  <option value="">Dubai - United Arab Emirates ( DXB )</option>
  <option value="">Dubbo, N.S.W. - Australia ( DBO )</option>
  <option value="">Dublin - Ireland ( DUB )</option>
  <option value="">Dubrovnik - Croatia ( DBV )</option>
  <option value="">Dubuque, IAВ - United States ( DBQ )</option>
  <option value="">Duluth, MNВ - United States ( DLH )</option>
  <option value="">Dumaguete - Philippines ( DGT )</option>
  <option value="">Dunedin - New Zealand ( DUD )</option>
  <option value="">Durango - Mexico ( DGO )</option>
  <option value="">Durango, COВ - United States ( DRO )</option>
  <option value="">Durban - South Africa ( DUR )</option>
  <option value="">Dushanbe - Tajikistan ( DYU )</option>
  <option value="">Dusseldorf - Germany ( DUS )</option>
  <option value="">Dutch Harbor, Un Island, AK - United States ( DUT )</option>
  <option value="">East London - South Africa ( ELS )</option>
  <option value="">East Midlands - England ( EMA )</option>
  <option value="">Eau Claire, WIВ - United States ( EAU )</option>
  <option value="">Edinburgh - Scotland ( EDI )</option>
  <option value="">Edmonton, AB - Canada ( YEG )</option>
  <option value="">Edmonton, ABВ - CanadaВ ( YEG )</option>
  <option value="">Eek, AKВ - United States ( EEK )</option>
  <option value="">Ekaterinburg, Siberia - Russia ( SVX )</option>
  <option value="">El Calafate - Argentina ( FTE )</option>
  <option value="">El Centro, CAВ - United States ( IPL )</option>
  <option value="">El Dorado, ARВ - United States ( ELD )</option>
  <option value="">El Paso, TXВ - United States ( ELP )</option>
  <option value="">El Salvador - Chile ( ESR )</option>
  <option value="">Elko, NVВ - United States ( EKO )</option>
  <option value="">Elmira, NYВ - United States ( ELM )</option>
  <option value="">Emerald, Qld. - Australia ( EMD )</option>
  <option value="">Enid, OKВ - United States ( WDG )</option>
  <option value="">Entebbe - Uganda ( EBB )</option>
  <option value="">Erfurt - Germany ( ERF )</option>
  <option value="">Erie, PAВ - United States ( ERI )</option>
  <option value="">Esbjerg - Denmark ( EBJ )</option>
  <option value="">Escanaba, MIВ - United States ( ESC )</option>
  <option value="">Eugene, ORВ - United States ( EUG )</option>
  <option value="">Eureka, CA - United States ( ACV )</option>
  <option value="">Evansville, INВ - United States ( EVV )</option>
  <option value="">Evenes - Norway ( EVE )</option>
  <option value="">Fairbanks, AKВ - United States ( FAI )</option>
  <option value="">Fargo, NDВ - United States ( FAR )</option>
  <option value="">Farmington, NMВ - United States ( FMN )</option>
  <option value="">Faro - Portugal ( FAO )</option>
  <option value="">Fayetteville, ARВ - United States ( XNA )</option>
  <option value="">Fayetteville, NCВ - United States ( FAY )</option>
  <option value="">Fernando de Noronha - Brazil ( FEN )</option>
  <option value="">Figari, Corsica - France ( FSC )</option>
  <option value="">Flagstaff, AZВ - United States ( FLG )</option>
  <option value="">Flin Flon, MB - Canada ( YFO )</option>
  <option value="">Flin Flon, MBВ - CanadaВ ( YFO )</option>
  <option value="">Flint, MIВ - United States ( FNT )</option>
  <option value="">Florence - Italy ( FLR )</option>
  <option value="">Florence, SCВ - United States ( FLO )</option>
  <option value="">Flores - Guatemala ( FRS )</option>
  <option value="">Fort Dodge, IAВ - United States ( FOD )</option>
  <option value="">Fort Lauderdale, FLВ - United States ( FLL )</option>
  <option value="">Fort Leonard Wood, MO - United States ( TBN )</option>
  <option value="">Fort McMurray, AB - Canada ( YMM )</option>
  <option value="">Fort McMurray, ABВ - CanadaВ ( YMM )</option>
  <option value="">Fort Myers, FLВ - United States ( RSW )</option>
  <option value="">Fort Nelson, BC - Canada ( YYE )</option>
  <option value="">Fort Nelson, BCВ - CanadaВ ( YYE )</option>
  <option value="">Fort Saint John, BC - Canada ( YXJ )</option>
  <option value="">Fort Saint John, BCВ - CanadaВ ( YXJ )</option>
  <option value="">Fort Smith, ARВ - United States ( FSM )</option>
  <option value="">Fort Smith, NWT - Canada ( YSM )</option>
  <option value="">Fort Smith, NWT - CanadaВ ( YSM )</option>
  <option value="">Fort Walton Beach, FLВ - United States ( VPS )</option>
  <option value="">Fort Wayne, INВ - United States ( FWA )</option>
  <option value="">Fort Yukon, AKВ - United States ( FYU )</option>
  <option value="">Fort-de-France - Martinique ( FDF )</option>
  <option value="">Frankfurt - Germany ( FRA )</option>
  <option value="">Fredericton, NB - Canada ( YFC )</option>
  <option value="">Fredericton, NBВ - CanadaВ ( YFC )</option>
  <option value="">Freeport, Grand Bahama Island - Bahamas ( FPO )</option>
  <option value="">Freetown - Sierra Leone ( FNA )</option>
  <option value="">Fresno, CAВ - United States ( FAT )</option>
  <option value="">Friedrichshafen - Germany ( FDH )</option>
  <option value="">Fukuoka - Japan ( FUK )</option>
  <option value="">Fukushima - Japan ( FKS )</option>
  <option value="">Funchal - Madeira ( FNC )</option>
  <option value="">Fuzhou - China ( FOC )</option>
  <option value="">Gainesville, FLВ - United States ( GNV )</option>
  <option value="">Gander, NF - Canada ( YQX )</option>
  <option value="">Gander, NFВ - CanadaВ ( YQX )</option>
  <option value="">Garden City, KS - United States ( GCK )</option>
  <option value="">Gaspe, PQ - Canada ( YGP )</option>
  <option value="">Gaspe, PQВ - CanadaВ ( YGP )</option>
  <option value="">Gdansk - Poland ( GDN )</option>
  <option value="">General Santos - Philippines ( GES )</option>
  <option value="">Geneva - Switzerland ( GVA )</option>
  <option value="">Genoa - Italy ( GOA )</option>
  <option value="">George Town, Great Exuma Island - Bahamas ( GGT )</option>
  <option value="">Georgetown - Guyana ( GEO )</option>
  <option value="">Gaborone - Botswana ( GBE )</option>
  <option value="">
    Georgetown, Grand Cayman Island - Cayman Islands ( GCM )
  </option>
  <option value="">Gillette, WYВ - United States ( GCC )</option>
  <option value="">Gisborne - New Zealand ( GIS )</option>
  <option value="">Gladstone, Qld. - Australia ( GLT )</option>
  <option value="">Glasgow - Scotland ( GLA )</option>
  <option value="">Glasgow - Scotland ( PIK )</option>
  <option value="">Glendive, MTВ - United States ( GDV )</option>
  <option value="">Gold Coast, Qld. - Australia ( OOL )</option>
  <option value="">Gothenburg - Sweden ( GOT )</option>
  <option value="">Gove, N.T. - Australia ( GOV )</option>
  <option value="">
    Governor's Harbour, Eleuthera Island - Bahamas ( GHB )
  </option>
  <option value="">Granada - Spain ( GRX )</option>
  <option value="">Grand Forks, NDВ - United States ( GFK )</option>
  <option value="">Grand Island, NEВ - United States ( GRI )</option>
  <option value="">Grand Junction, COВ - United States ( GJT )</option>
  <option value="">Grand Rapids, MIВ - United States ( GRR )</option>
  <option value="">Grande Prairie, AB - Canada ( YQU )</option>
  <option value="">Grande Prairie, ABВ - CanadaВ ( YQU )</option>
  <option value="">Graz - Austria ( GRZ )</option>
  <option value="">Great Bend, KSВ - United States ( GBD )</option>
  <option value="">Great Falls, MTВ - United States ( GTF )</option>
  <option value="">Green Bay, WIВ - United States ( GRB )</option>
  <option value="">Greenbrier, WV - United States ( LWB )</option>
  <option value="">Greensboro, NCВ - United States ( GSO )</option>
  <option value="">Greenville, MSВ - United States ( GLH )</option>
  <option value="">Greenville, NCВ - United States ( PGV )</option>
  <option value="">Greenville, SCВ - United States ( GSP )</option>
  <option value="">Griffith, N.S.W. - Australia ( GFF )</option>
  <option value="">Guadalajara - Mexico ( GDL )</option>
  <option value="">Guangzhou - China ( CAN )</option>
  <option value="">Guatemala City - Guatemala ( GUA )</option>
  <option value="">Guayaquil - Ecuador ( GYE )</option>
  <option value="">Guaymas - Mexico ( GYM )</option>
  <option value="">Guernsey - Channel Islands ( GCI )</option>
  <option value="">Guilin - China ( KWL )</option>
  <option value="">Gulfport, MSВ - United States ( GPT )</option>
  <option value="">Gunnison, COВ - United States ( GUC )</option>
  <option value="">Gustavia - St. Barts ( SBH )</option>
  <option value="">Hagerstown, MDВ - United States ( HGR )</option>
  <option value="">Haikou, Hainan Island - China ( HAK )</option>
  <option value="">Hailar - China ( HLD )</option>
  <option value="">Hakodate - Japan ( HKD )</option>
  <option value="">Halifax, NS - Canada ( YHZ )</option>
  <option value="">Halifax, NSВ - CanadaВ ( YHZ )</option>
  <option value="">Halmstad - Sweden ( HAD )</option>
  <option value="">Hamburg - Germany ( HAM )</option>
  <option value="">Hamilton - Bermuda ( BDA )</option>
  <option value="">Hamilton - New Zealand ( HLZ )</option>
  <option value="">
    Hamilton Island, Whitsunday Island, Qld. - Australia ( HTI )
  </option>
  <option value="">Hamilton, ON - Canada ( YHM )</option>
  <option value="">Hamilton, ONВ - CanadaВ ( YHM )</option>
  <option value="">Hammerfest - Norway ( HFT )</option>
  <option value="">Hana, Maui, HI - United States ( HNM )</option>
  <option value="">Hancock, MIВ - United States ( CMX )</option>
  <option value="">Hanga Roa, Easter Island - Chile ( IPC )</option>
  <option value="">Hangzhou - China ( HGH )</option>
  <option value="">Hannover - Germany ( HAJ )</option>
  <option value="">Hanoi - Vietnam ( HAN )</option>
  <option value="">Harare - Zimbabwe ( HRE )</option>
  <option value="">Harbin - China ( HRB )</option>
  <option value="">Harlingen, TXВ - United States ( HRL )</option>
  <option value="">Harrisburg, PAВ - United States ( MDT )</option>
  <option value="">Harrison, ARВ - United States ( HRO )</option>
  <option value="">Hartford, CTВ - United States ( BDL )</option>
  <option value="">Hat Yai - Thailand ( HDY )</option>
  <option value="">Haugesund - Norway ( HAU )</option>
  <option value="">Havana - Cuba ( HAV )</option>
  <option value="">Havre, MTВ - United States ( HVR )</option>
  <option value="">Hays, KS - United States ( HYS )</option>
  <option value="">Hefei - China ( HFE )</option>
  <option value="">Helena, MTВ - United States ( HLN )</option>
  <option value="">Helsingborg - Sweden ( AGH )</option>
  <option value="">Helsinki - Finland ( HEL )</option>
  <option value="">Hemavan - Sweden ( HMV )</option>
  <option value="">Hengchun - Taiwan ( HCN )</option>
  <option value="">Heraklion, Crete - Greece ( HER )</option>
  <option value="">Hermosillo - Mexico ( HMO )</option>
  <option value="">Hibbing, MNВ - United States ( HIB )</option>
  <option value="">Hilo, HawaiiВ - United States ( Big )</option>
  <option value="">Hilton Head Island, SCВ - United States ( HHH )</option>
  <option value="">Ho Chi Minh City (Saigon) - Vietnam ( SGN )</option>
  <option value="">Hobart, Tas. - Australia ( HBA )</option>
  <option value="">Hobbs, NMВ - United States ( HOB )</option>
  <option value="">Hof - Germany ( HOQ )</option>
  <option value="">Hohhot - China ( HET )</option>
  <option value="">Hokitika - New Zealand ( HKK )</option>
  <option value="">Homer, AK - United States ( HOM )</option>
  <option value="">Hong Kong - China ( HKG )</option>
  <option value="">Honiara, Guadalcanal - Solomon Islands ( HIR )</option>
  <option value="">Honolulu, Oahu, HI - United States ( HNL )</option>
  <option value="">Hoolehua, Molokai, HI - United States ( MKK )</option>
  <option value="">Horn Island, Qld. - Australia ( HID )</option>
  <option value="">Hot Springs, ARВ - United States ( HOT )</option>
  <option value="">Houmt Souk - Tunisia ( DJE )</option>
  <option value="">Houston, TXВ - United States ( EFD )</option>
  <option value="">Houston, TXВ - United States ( HOU )</option>
  <option value="">Houston, TXВ - United States ( IAH )</option>
  <option value="">Hualien - Taiwan ( HUN )</option>
  <option value="">Hue - Vietnam ( HUI )</option>
  <option value="">Humberside - England ( HUY )</option>
  <option value="">Huntington, WVВ - United States ( HTS )</option>
  <option value="">Huntsville, ALВ - United States ( HSV )</option>
  <option value="">Hurghada - Egypt ( HRG )</option>
  <option value="">Huron, SD - United States ( HON )</option>
  <option value="">Hyannis, MAВ - United States ( HYA )</option>
  <option value="">Hyderabad - India ( HYD )</option>
  <option value="">Ibadan - Nigeria ( IBA )</option>
  <option value="">Ibiza - Spain ( IBZ )</option>
  <option value="">Idaho Falls, IDВ - United States ( IDA )</option>
  <option value="">Ikaria Island - Greece ( JIK )</option>
  <option value="">Iloilo - Philippines ( ILO )</option>
  <option value="">Indianapolis, INВ - United States ( IND )</option>
  <option value="">Innsbruck - Austria ( INN )</option>
  <option value="">International Falls, MNВ - United States ( INL )</option>
  <option value="">Invercargill - New Zealand ( IVC )</option>
  <option value="">Inverness - Scotland ( INV )</option>
  <option value="">Inyokern, CAВ - United States ( IYK )</option>
  <option value="">Ioannina - Greece ( IOA )</option>
  <option value="">Ipoh - Malaysia ( IPH )</option>
  <option value="">Iqaluit, Nunavut - Canada ( YFB )</option>
  <option value="">Iqaluit, NunavutВ - CanadaВ ( YFB )</option>
  <option value="">Irkutsk, Siberia - Russia ( IKT )</option>
  <option value="">Iron Mountain, MIВ - United States ( IMT )</option>
  <option value="">Ironwood, MI - United States ( IWD )</option>
  <option value="">Islamabad-Rawalpindi - Pakistan ( ISB )</option>
  <option value="">Islay Island - Scotland ( ILY )</option>
  <option value="">Islip, NYВ - United States ( ISP )</option>
  <option value="">Istanbul - Turkey ( IST )</option>
  <option value="">Istanbul - Turkey ( SAW )</option>
  <option value="">Ithaca, NYВ - United States ( ITH )</option>
  <option value="">Ivalo - Finland ( IVL )</option>
  <option value="">Iwami - Japan ( IWJ )</option>
  <option value="">Ixtapa - Mexico ( ZIH )</option>
  <option value="">Izmir - Turkey ( ADB )</option>
  <option value="">Izumo - Japan ( IZO )</option>
  <option value="">Jackson Hole, WYВ - United States ( JAC )</option>
  <option value="">Jackson, MSВ - United States ( JAN )</option>
  <option value="">Jackson, TNВ - United States ( MKL )</option>
  <option value="">Jacksonville, FLВ - United States ( JAX )</option>
  <option value="">Jacksonville, NCВ - United States ( OAJ )</option>
  <option value="">Jakarta, Java - Indonesia ( CGK )</option>
  <option value="">Jakarta, Java - Indonesia ( JKT - All Airports )</option>
  <option value="">Jalapa - Mexico ( JAL )</option>
  <option value="">Jamestown, NDВ - United States ( JMS )</option>
  <option value="">Jamestown, NYВ - United States ( JHW )</option>
  <option value="">Jeddah - Saudi Arabia ( JED )</option>
  <option value="">Jeju, Korea - Republic of ( CJU )</option>
  <option value="">Jerez de La Frontera - Spain ( XRY )</option>
  <option value="">Jersey - Channel Islands ( JER )</option>
  <option value="">Jiamusi - China ( JMU )</option>
  <option value="">Jijiga - Ethiopia ( JIJ )</option>
  <option value="">Joensuu - Finland ( JOE )</option>
  <option value="">Johannesburg - South Africa ( JNB )</option>
  <option value="">Johnstown, PAВ - United States ( JST )</option>
  <option value="">Johor Bahru - Malaysia ( JHB )</option>
  <option value="">Jonesboro, ARВ - United States ( JBR )</option>
  <option value="">Jonkoping - Sweden ( JKG )</option>
  <option value="">Joplin, MOВ - United States ( JLN )</option>
  <option value="">Juneau, AKВ - United States ( JNU )</option>
  <option value="">Jyvaskyla - Finland ( JYV )</option>
  <option value="">Kabul - Afghanistan ( KBL )</option>
  <option value="">Kagoshima - Japan ( KOJ )</option>
  <option value="">Kahului, Maui, HIВ - United States ( OGG )</option>
  <option value="">Kailua-Kona, HI - United States ( KOA )</option>
  <option value="">Kaitaia - New Zealand ( KAT )</option>
  <option value="">Kajaani - Finland ( KAJ )</option>
  <option value="">Kalamazoo, MIВ - United States ( AZO )</option>
  <option value="">Kalaupapa, Molokai, HI - United States ( LUP )</option>
  <option value="">Kalgoorlie, W.A. - Australia ( KGI )</option>
  <option value="">Kalibo - Philippines ( KLO )</option>
  <option value="">Kaliningrad - Russia ( KGD )</option>
  <option value="">Kalispell, MTВ - United States ( FCA )</option>
  <option value="">Kalmar - Sweden ( KLR )</option>
  <option value="">Kamloops, BC - Canada ( YKA )</option>
  <option value="">Kamloops, BCВ - CanadaВ ( YKA )</option>
  <option value="">Kamuela, HawaiiВ - United States ( KOA )</option>
  <option value="">Kansas City, MOВ - United States ( MCI )</option>
  <option value="">Kaohsiung - Taiwan ( KHH )</option>
  <option value="">Kapalua, Maui, HI - United States ( JHM )</option>
  <option value="">Karachi - Pakistan ( KHI )</option>
  <option value="">Karaganda - Kazakhstan ( KGF )</option>
  <option value="">Karlstad - Sweden ( KSD )</option>
  <option value="">Kochi - India ( COK )</option>
  <option value="">Karratha, W.A. - Australia ( KTA )</option>
  <option value="">Karup - Denmark ( KRP )</option>
  <option value="">Kashi - China ( KHG )</option>
  <option value="">Kathmandu - Nepal ( KTM )</option>
  <option value="">Katowice - Poland ( KTW )</option>
  <option value="">Kearney, NEВ - United States ( EAR )</option>
  <option value="">Kelowna, BC - Canada ( YLW )</option>
  <option value="">Kelowna, BCВ - CanadaВ ( YLW )</option>
  <option value="">Kenai, AKВ - United States ( ENA )</option>
  <option value="">Kenora, ON - Canada ( YQK )</option>
  <option value="">Kenora, ONВ - CanadaВ ( YQK )</option>
  <option value="">Kerikeri - New Zealand ( KKE )</option>
  <option value="">Ketchikan, AKВ - United States ( KTN )</option>
  <option value="">Key West, FLВ - United States ( EYW )</option>
  <option value="">Kharkov - Ukraine ( HRK )</option>
  <option value="">Khartoum - Sudan ( KRT )</option>
  <option value="">Khon Kaen - Thailand ( KKC )</option>
  <option value="">Kiel - Germany ( KEL )</option>
  <option value="">Kiev - Ukraine ( KBP )</option>
  <option value="">Kigali - Rwanda ( KGL )</option>
  <option value="">Killeen, TXВ - United States ( GRK )</option>
  <option value="">King Salmon, AK - United States ( AKN )</option>
  <option value="">Kingman, AZВ - United States ( IGM )</option>
  <option value="">Kingscote, Kangaroo Island, S.A. - Australia ( KGC )</option>
  <option value="">Kingston - Jamaica ( KIN )</option>
  <option value="">Kingston - Jamaica ( KTP )</option>
  <option value="">Kingston, ON - Canada ( YGK )</option>
  <option value="">Kingston, ONВ - CanadaВ ( YGK )</option>
  <option value="">Kingstown - St. Vincent ( SVD )</option>
  <option value="">Kinshasa - Zaire ( FIH )</option>
  <option value="">Kirksville, MOВ - United States ( IRK )</option>
  <option value="">Kirkwall, Orkney Islands - Scotland ( KOI )</option>
  <option value="">Kiruna - Sweden ( KRN )</option>
  <option value="">Kisangani - Zaire ( FKI )</option>
  <option value="">Kittila - Finland ( KTT )</option>
  <option value="">Klagenfurt - Austria ( KLU )</option>
  <option value="">Klamath Falls, ORВ - United States ( LMT )</option>
  <option value="">Knoxville, TNВ - United States ( TYS )</option>
  <option value="">Kodiak, AKВ - United States ( ADQ )</option>
  <option value="">Koh Samui - Thailand ( USM )</option>
  <option value="">Kokkola - Finland ( KOK )</option>
  <option value="">Komatsu - Japan ( KMQ )</option>
  <option value="">Koror - Palau ( ROR )</option>
  <option value="">Kos - Greece ( KGS )</option>
  <option value="">Kosrae - Micronesia ( KSA )</option>
  <option value="">Kota Bharu - Malaysia ( KBR )</option>
  <option value="">Kota Kinabalu, Sabah - Malaysia ( BKI )</option>
  <option value="">Krabi - Thailand ( KBV )</option>
  <option value="">Krakow - Poland ( KRK )</option>
  <option value="">Kralendijk - Bonaire ( BON )</option>
  <option value="">Kramfors - Sweden ( KRF )</option>
  <option value="">Kristiansand - Norway ( KRS )</option>
  <option value="">Kristianstad - Sweden ( KID )</option>
  <option value="">Kuala Lumpur - Malaysia ( KUL )</option>
  <option value="">Kuala Terengganu - Malaysia ( TGG )</option>
  <option value="">Kuantan - Malaysia ( KUA )</option>
  <option value="">Kuching, Sarawak - Malaysia ( KCH )</option>
  <option value="">Kumamoto - Japan ( KMJ )</option>
  <option value="">Kunming - China ( KMG )</option>
  <option value="">Kuopio - Finland ( KUO )</option>
  <option value="">Kushiro - Japan ( KUH )</option>
  <option value="">Kuwait - Kuwait ( KWI )</option>
  <option value="">Kzyl Orda - Kazakhstan ( KZO )</option>
  <option value="">La Coruna - Spain ( LCG )</option>
  <option value="">La Crosse, WIВ - United States ( LSE )</option>
  <option value="">La Paz - Mexico ( LAP )</option>
  <option value="">La Paz - Bolivia ( LPB )</option>
  <option value="">La Romana - Dominican Republic ( LRM )</option>
  <option value="">La Serena - Chile ( LSC )</option>
  <option value="">Lafayette, LAВ - United States ( LFT )</option>
  <option value="">Lagos - Nigeria ( LOS )</option>
  <option value="">Lahad Datu, Sabah - Malaysia ( LDU )</option>
  <option value="">Lahore - Pakistan ( LHE )</option>
  <option value="">Lake Charles, LAВ - United States ( LCH )</option>
  <option value="">Lake Havasu City, AZВ - United States ( HII )</option>
  <option value="">Lamezia Terme - Italy ( SUF )</option>
  <option value="">Lanai City, Lanai, HI - United States ( LNY )</option>
  <option value="">Lancaster, PAВ - United States ( LNS )</option>
  <option value="">Langkawi - Malaysia ( LGK )</option>
  <option value="">Lannion - France ( LAI )</option>
  <option value="">Lansing, MIВ - United States ( LAN )</option>
  <option value="">Lanzhou - China ( LHW )</option>
  <option value="">Laramie, WYВ - United States ( LAR )</option>
  <option value="">Laredo, TXВ - United States ( LRD )</option>
  <option value="">Larnaca - Cyprus ( LCA )</option>
  <option value="">Las Cruces, NMВ - United States ( LRU )</option>
  <option value="">
    Las Palmas, Grand Canary Island - Canary Islands ( LPA )
  </option>
  <option value="">Las Vegas, NVВ - United States ( LAS )</option>
  <option value="">Latrobe, PAВ - United States ( LBE )</option>
  <option value="">Launceston, Tas. - Australia ( LST )</option>
  <option value="">Laurel, MSВ - United States ( PIB )</option>
  <option value="">Lawton, OKВ - United States ( LAW )</option>
  <option value="">Lazaro Cardenas - Mexico ( LZC )</option>
  <option value="">Le Havre - France ( LEH )</option>
  <option value="">Lebanon, NHВ - United States ( LEB )</option>
  <option value="">Leeds - England ( LBA )</option>
  <option value="">Legaspi - Philippines ( LGP )</option>
  <option value="">Leipzig - Germany ( LEJ )</option>
  <option value="">Leon - Mexico ( BJX )</option>
  <option value="">Leon - Spain ( LEN )</option>
  <option value="">Lerwick, Shetland Islands - Scotland ( LSI )</option>
  <option value="">Lethbridge, AB - Canada ( YQL )</option>
  <option value="">Lethbridge, ABВ - CanadaВ ( YQL )</option>
  <option value="">Lewiston, IDВ - United States ( LWS )</option>
  <option value="">Lewiston, MEВ - United States ( LEW )</option>
  <option value="">Lewistown, MTВ - United States ( LWT )</option>
  <option value="">Lexington, KYВ - United States ( LEX )</option>
  <option value="">Lhasa, Tibet - China ( LXA )</option>
  <option value="">Liberal, KS - United States ( LBL )</option>
  <option value="">Liberia - Costa Rica ( LIR )</option>
  <option value="">Libreville - Gabon ( LBV )</option>
  <option value="">Lihue, Kauai, HI - United States ( LIH )</option>
  <option value="">Lijiang City - China ( LJG )</option>
  <option value="">Lille - France ( LIL )</option>
  <option value="">Lilongwe - Malawi ( LLW )</option>
  <option value="">Lima - Peru ( LIM )</option>
  <option value="">Limoges - France ( LIG )</option>
  <option value="">Lincang - China ( LNJ )</option>
  <option value="">Lincoln, NEВ - United States ( LNK )</option>
  <option value="">Linkoping - Sweden ( LPI )</option>
  <option value="">Linz - Austria ( LNZ )</option>
  <option value="">Lisbon - Portugal ( LIS )</option>
  <option value="">Little Rock, ARВ - United States ( LIT )</option>
  <option value="">Liverpool - England ( LPL )</option>
  <option value="">Ljubljana - Slovenia ( LJU )</option>
  <option value="">Logrono - Spain ( RJL )</option>
  <option value="">Lome - Togo ( LFW )</option>
  <option value="">London - England ( LCY )</option>
  <option value="">London - England ( LGW )</option>
  <option value="">London - England ( LHR )</option>
  <option value="">London - England ( LON - All Airports )</option>
  <option value="">London - England ( STN )</option>
  <option value="">London, ON - Canada ( YXU )</option>
  <option value="">London, ONВ - CanadaВ ( YXU )</option>
  <option value="">Londonderry - Northern Ireland ( LDY )</option>
  <option value="">Long Banga - Malaysia ( LBP )</option>
  <option value="">Long Beach, CAВ - United States ( LGB )</option>
  <option value="">Longreach, Qld. - Australia ( LRE )</option>
  <option value="">Longview, TXВ - United States ( GGG )</option>
  <option value="">Longyearbyen, Svalbard - Norway ( LYR )</option>
  <option value="">Loreto - Mexico ( LTO )</option>
  <option value="">Lorient - France ( LRT )</option>
  <option value="">Los Angeles, CAВ - United States ( LAX )</option>
  <option value="">Los Angeles, CAВ - United States ( QLA-All )</option>
  <option value="">Los Cabos - Mexico ( SJD )</option>
  <option value="">
    Louisville, KY, United States - United States ( SDF )
  </option>
  <option value="">Lourdes - France ( LDE )</option>
  <option value="">Luanda - Angola ( LAD )</option>
  <option value="">Lubbock, TXВ - United States ( LBB )</option>
  <option value="">Lubumbashi - Zaire ( FBM )</option>
  <option value="">Lugano - Switzerland ( LUG )</option>
  <option value="">Lugansk - Ukraine ( VSG )</option>
  <option value="">Lukla - Nepal ( LUA )</option>
  <option value="">Lulea - Sweden ( LLA )</option>
  <option value="">Lusaka - Zambia ( LUN )</option>
  <option value="">Luton - England ( LTN )</option>
  <option value="">Luxembourg - Luxembourg ( LUX )</option>
  <option value="">Luxor - Egypt ( LXR )</option>
  <option value="">Lycksele - Sweden ( LYC )</option>
  <option value="">Lynchburg, VAВ - United States ( LYH )</option>
  <option value="">Lyon - France ( LYS )</option>
  <option value="">Mackay, Qld. - Australia ( MKY )</option>
  <option value="">Macon, GAВ - United States ( MCN )</option>
  <option value="">Madison, WIВ - United States ( MSN )</option>
  <option value="">Madrid - Spain ( MAD )</option>
  <option value="">Mae Hong Son - Thailand ( HGN )</option>
  <option value="">Magdalens Islands, PQ - ( )</option>
  <option value="">Mahebourg - Mauritius ( MRU )</option>
  <option value="">Majuro - Marshall Islands ( MAJ )</option>
  <option value="">Mala Mala - South Africa ( AAM )</option>
  <option value="">Malabo, Bioko Island - Equatorial Guinea ( SSG )</option>
  <option value="">Malaga - Spain ( AGP )</option>
  <option value="">Male - Maldives ( MLE )</option>
  <option value="">Malmo - Sweden ( MMA - All Airports )</option>
  <option value="">Malmo - Sweden ( MMX )</option>
  <option value="">Managua - Nicaragua ( MGA )</option>
  <option value="">Manama - Bahrain ( BAH )</option>
  <option value="">Manaus - Brazil ( MAO )</option>
  <option value="">Manchester - England ( MAN )</option>
  <option value="">Manchester, NHВ - United States ( MHT )</option>
  <option value="">Mangrove Cay, Island - Bahamas ( MAY )</option>
  <option value="">Manhattan, KSВ - United States ( MHK )</option>
  <option value="">Manila - Philippines ( MNL )</option>
  <option value="">Mandalay - Myanmar ( MDL )</option>
  <option value="">Manistee, MIВ - United States ( MBL )</option>
  <option value="">Manzanillo - Mexico ( ZLO )</option>
  <option value="">Manzini - Swaziland ( MTS )</option>
  <option value="">Mao, Minorca - Spain ( MAH )</option>
  <option value="">Maputo - Mozambique ( MPM )</option>
  <option value="">Maracaibo - Venezuela ( MAR )</option>
  <option value="">Mariehamn, Aland - Finland ( MHQ )</option>
  <option value="">Marilia - Brazil ( MII )</option>
  <option value="">Marion, ILВ - United States ( MWA )</option>
  <option value="">Mariupol - Ukraine ( MPW )</option>
  <option value="">Maroochydore, Qld. - Australia ( MCY )</option>
  <option value="">Marquette, MIВ - United States ( MQT )</option>
  <option value="">Marrakech - Morocco ( RAK )</option>
  <option value="">Marrakech - Morocco ( RAK )</option>
  <option value="">Marseille - France ( MRS )</option>
  <option value="">Marsh Harbour, Abaco Island - Bahamas ( MHH )</option>
  <option value="">Martha's Vineyard, MAВ - United States ( MVY )</option>
  <option value="">Maseru - Lesotho ( MSU )</option>
  <option value="">Mason City, IAВ - United States ( MCW )</option>
  <option value="">Massena, NYВ - United States ( MSS )</option>
  <option value="">Matsu - Taiwan ( MFK )</option>
  <option value="">Matsuyama - Japan ( MYJ )</option>
  <option value="">Mazatlan - Mexico ( MZT )</option>
  <option value="">McAllen, TXВ - United States ( MFE )</option>
  <option value="">McCook, NEВ - United States ( MCK )</option>
  <option value="">Medan, Sumatra - Indonesia ( MES )</option>
  <option value="">Medellin - Colombia ( MDE )</option>
  <option value="">Medford, ORВ - United States ( MFR )</option>
  <option value="">Medicine Hat, AB - Canada ( YXH )</option>
  <option value="">Medicine Hat, ABВ - CanadaВ ( YXH )</option>
  <option value="">Melbourne, FLВ - United States ( MLB )</option>
  <option value="">Avalon - Australia ( AVV )</option>
  <option value="">Melbourne - Australia ( MEL )</option>
  <option value="">Melilla - Spain ( MLN )</option>
  <option value="">Memanbetsu - Japan ( MMB )</option>
  <option value="">Memphis, TNВ - United States ( MEM )</option>
  <option value="">Mendoza - Argentina ( MDZ )</option>
  <option value="">Merida - Mexico ( MID )</option>
  <option value="">Meridian, MSВ - United States ( MEI )</option>
  <option value="">Merimbula, N.S.W. - Australia ( MIM )</option>
  <option value="">Metz - France ( ETZ )</option>
  <option value="">Mexicali - Mexico ( MXL )</option>
  <option value="">Mexico City - Mexico ( MEX )</option>
  <option value="">Miami, FLВ - United States ( MIA )</option>
  <option value="">Mian Yang - China ( MIG )</option>
  <option value="">Midland, TXВ - United States ( MAF )</option>
  <option value="">Mikonos - Greece ( JMK )</option>
  <option value="">Milan - Italy ( LIN )</option>
  <option value="">Milan - Italy ( MIL - All )</option>
  <option value="">Milan - Italy ( MXP )</option>
  <option value="">Mildura, Vic. - Australia ( MQL )</option>
  <option value="">Miles City, MT - United States ( MLS )</option>
  <option value="">Milwaukee, WIВ - United States ( MKE )</option>
  <option value="">Minneapolis, MNВ - United States ( MSP )</option>
  <option value="">Minot, NDВ - United States ( MOT )</option>
  <option value="">Minsk - Belarus ( MHP )</option>
  <option value="">Minsk - Belarus ( MSQ )</option>
  <option value="">Miri, Sarawak - Malaysia ( MYY )</option>
  <option value="">Misawa - Japan ( MSJ )</option>
  <option value="">Missoula, MTВ - United States ( MSO )</option>
  <option value="">Miyazaki - Japan ( KMI )</option>
  <option value="">Mobile, ALВ - United States ( MOB )</option>
  <option value="">Modesto, CAВ - United States ( MOD )</option>
  <option value="">Mogadishu - Somalia ( MGQ )</option>
  <option value="">Moline, ILВ - United States ( MLI )</option>
  <option value="">Mombasa - Kenya ( MBA )</option>
  <option value="">Monastir - Tunisia ( MIR )</option>
  <option value="">Monclova - Mexico ( LOV )</option>
  <option value="">Moncton, NB - Canada ( YQM )</option>
  <option value="">Moncton, NBВ - CanadaВ ( YQM )</option>
  <option value="">Monroe, LAВ - United States ( MLU )</option>
  <option value="">Monrovia - Liberia ( ROB )</option>
  <option value="">Mont-Joli, PQ - Canada ( YYY )</option>
  <option value="">Mont-Joli, PQВ - CanadaВ ( YYY )</option>
  <option value="">Montego Bay - Jamaica ( MBJ )</option>
  <option value="">Monterey, CAВ - United States ( MRY )</option>
  <option value="">Monterrey - Mexico ( MTY )</option>
  <option value="">Montevideo - Uruguay ( MVD )</option>
  <option value="">Montgomery, ALВ - United States ( MGM )</option>
  <option value="">Montpellier - France ( MPL )</option>
  <option value="">Montreal, PQ - Canada ( YMQ-All )</option>
  <option value="">Montreal, PQ - Canada ( YUL )</option>
  <option value="">Montreal, PQВ - CanadaВ ( YMQВ AllВ )</option>
  <option value="">Montreal, PQВ - CanadaВ ( YUL )</option>
  <option value="">Montrose, COВ - United States ( MTJ )</option>
  <option value="">Mora - Sweden ( MXX )</option>
  <option value="">Moree, N.S.W. - Australia ( MRZ )</option>
  <option value="">Morelia - Mexico ( MLM )</option>
  <option value="">Morgantown, WVВ - United States ( MGW )</option>
  <option value="">Moroni - Comoro Islands ( HAH )</option>
  <option value="">Moruya, N.S.W. - Australia ( MYA )</option>
  <option value="">Moscow - Russia ( MOW All )</option>
  <option value="">Moscow - Russia ( SVO )</option>
  <option value="">Moscow - Russia ( DME )</option>
  <option value="">Moscow - Russia ( VKO )</option>
  <option value="">Moses Lake, WA - United States ( MWH )</option>
  <option value="">Mount Gambier, S.A. - Australia ( MGB )</option>
  <option value="">Mount Isa, Qld. - Australia ( ISA )</option>
  <option value="">Mudanjiang - China ( MDG )</option>
  <option value="">Mulhouse - France ( EAP - All )</option>
  <option value="">Mulhouse - France ( MLH )</option>
  <option value="">Mulu - Malaysia ( MZV )</option>
  <option value="">Mumbai (Bombay) - India ( BOM )</option>
  <option value="">Munich - Germany ( MUC )</option>
  <option value="">Munster - Germany ( FMO )</option>
  <option value="">Murcia - Spain ( MJV )</option>
  <option value="">Murmansk - Russia ( MMK )</option>
  <option value="">Muscat - Oman ( MCT )</option>
  <option value="">Muscle Shoals, AL - United States ( MSL )</option>
  <option value="">Muskegon, MIВ - United States ( MKG )</option>
  <option value="">Myrtle Beach, SCВ - United States ( MYR )</option>
  <option value="">Mytilene, Lesbos Island - Greece ( MJT )</option>
  <option value="">N'Djamena - Chad ( NDJ )</option>
  <option value="">Nadi - Fiji ( NAN )</option>
  <option value="">Nador - Morocco ( NDR )</option>
  <option value="">Nagasaki - Japan ( NGS )</option>
  <option value="">Nagoya - Japan ( NGO )</option>
  <option value="">Nagoya - Japan ( NKM )</option>
  <option value="">Naha, Okinawa - Japan ( OKA )</option>
  <option value="">Nairobi - Kenya ( NBO )</option>
  <option value="">Nakhon Si Thammarat - Thailand ( NST )</option>
  <option value="">Nanaimo, BC - Canada ( YCD )</option>
  <option value="">Nanaimo, BCВ - CanadaВ ( YCD )</option>
  <option value="">Nanchang - China ( KHN )</option>
  <option value="">Taiwan ( LZN )</option>
  <option value="">Nanjing - China ( NKG )</option>
  <option value="">Nanki Shirahama - Japan ( SHM )</option>
  <option value="">Nanning - China ( NNG )</option>
  <option value="">Nantes - France ( NTE )</option>
  <option value="">Nantucket, MAВ - United States ( ACK )</option>
  <option value="">Napier - New Zealand ( NPE )</option>
  <option value="">Naples - Italy ( NAP )</option>
  <option value="">Naples, FLВ - United States ( APF )</option>
  <option value="">Narrabri, N.S.W. - Australia ( NAA )</option>
  <option value="">Narrandera, N.S.W. - Australia ( NRA )</option>
  <option value="">Narvik - Norway ( NVK )</option>
  <option value="">Naryan Mar - Russia ( NNM )</option>
  <option value="">Nashville, TNВ - United States ( BNA )</option>
  <option value="">Nassau - Bahamas ( NAS )</option>
  <option value="">Nassau - Bahamas ( PID )</option>
  <option value="">Naze, Amami-O Island - Japan ( ASJ )</option>
  <option value="">Nelson - New Zealand ( NSN )</option>
  <option value="">Nelspruit - South Africa ( MQP )</option>
  <option value="">New Bern, NCВ - United States ( EWN )</option>
  <option value="">New Haven, CTВ - United States ( HVN )</option>
  <option value="">New Orleans, LAВ - United States ( MSY )</option>
  <option value="">New York, NYВ - United States ( JFK )</option>
  <option value="">New York, NYВ - United States ( LGA )</option>
  <option value="">New York, NYВ - United States ( NYCВ -All )</option>
  <option value="">Newark, NJВ - United States ( EWR )</option>
  <option value="">Newburgh, NYВ - United States ( SWF )</option>
  <option value="">Newcastle - England ( NCL )</option>
  <option value="">Newcastle, N.S.W. - Australia ( NTL )</option>
  <option value="">Newman, W.A. - Australia ( ZNE )</option>
  <option value="">Newport News, VAВ - United States ( PHF )</option>
  <option value="">Niamey - Niger ( NIM )</option>
  <option value="">Nice - France ( NCE )</option>
  <option value="">Niigata - Japan ( KIJ )</option>
  <option value="">Ningbo - China ( NGB )</option>
  <option value="">Nizhniy Novgorod - Russia ( GOJ )</option>
  <option value="">Nome, AKВ - United States ( OME )</option>
  <option value="">Norfolk, VAВ - United States ( ORF )</option>
  <option value="">Norrkoping - Sweden ( NRK )</option>
  <option value="">North Bay, ON - Canada ( YYB )</option>
  <option value="">North Bay, ONВ - CanadaВ ( YYB )</option>
  <option value="">North Bend, ORВ - United States ( OTH )</option>
  <option value="">North Eleuthera - Bahamas ( ELH )</option>
  <option value="">North Platte, NEВ - United States ( LBF )</option>
  <option value="">Norwich - England ( NWI )</option>
  <option value="">Nouakchott - Mauritania ( NKC )</option>
  <option value="">Noumea - New Caledonia ( GEA )</option>
  <option value="">Noumea - New Caledonia ( NOU )</option>
  <option value="">Novosibirsk, Siberia - Russia ( OVB )</option>
  <option value="">Nuevo Laredo - Mexico ( NLD )</option>
  <option value="">Nuremberg - Germany ( NUE )</option>
  <option value="">Oakland, CAВ - United States ( OAK )</option>
  <option value="">Oaxaca - Mexico ( OAX )</option>
  <option value="">Obihiro - Japan ( OBO )</option>
  <option value="">Ocho Rios - Jamaica ( OCJ )</option>
  <option value="">Odate Noshiro - Japan ( ONJ )</option>
  <option value="">Odessa - Ukraine ( ODS )</option>
  <option value="">Ogdensburg, NYВ - United States ( OGS )</option>
  <option value="">Oita - Japan ( OIT )</option>
  <option value="">Oklahoma City, OKВ - United States ( OKC )</option>
  <option value="">Olbia, Sardinia - Italy ( OLB )</option>
  <option value="">Olympic Dam, S.A. - Australia ( OLP )</option>
  <option value="">Omaha, NEВ - United States ( OMA )</option>
  <option value="">Omsk, Siberia - Russia ( OMS )</option>
  <option value="">Ontario, CAВ - United States ( ONT )</option>
  <option value="">Orange County, CAВ - United States ( SNA )</option>
  <option value="">Orange, N.S.W. - Australia ( OAG )</option>
  <option value="">Oranjestad - Aruba ( AUA )</option>
  <option value="">Oranjestad - St. Eustatius ( EUX )</option>
  <option value="">Orebro - Sweden ( ORB )</option>
  <option value="">Orlando, FLВ - United States ( MCO )</option>
  <option value="">Ornskoldsvik - Sweden ( OER )</option>
  <option value="">Osaka - Japan ( ITM )</option>
  <option value="">Osaka - Japan ( KIX )</option>
  <option value="">Osaka - Japan ( OSA - All Airports )</option>
  <option value="">Oshkosh, WIВ - United States ( OSH )</option>
  <option value="">Oslo - Norway ( OSL )</option>
  <option value="">Osorno - Chile ( ZOS )</option>
  <option value="">Ostersund - Sweden ( OSD )</option>
  <option value="">Ostrava - Czech Republic ( OSR )</option>
  <option value="">Ottawa, ON - Canada ( YOW )</option>
  <option value="">Ottawa, ONВ - CanadaВ ( YOW )</option>
  <option value="">Ouagadougou - Burkina Faso ( OUA )</option>
  <option value="">Oulu - Finland ( OUL )</option>
  <option value="">Owensboro, KYВ - United States ( OWB )</option>
  <option value="">Oxnard, CAВ - United States ( OXR )</option>
  <option value="">Paderborn - Germany ( PAD )</option>
  <option value="">Paducah, KYВ - United States ( PAH )</option>
  <option value="">Page, AZ - United States ( PGA )</option>
  <option value="">Pago Pago, Tutuila - American Samoa ( PPG )</option>
  <option value="">Pajala - Sweden ( PJA )</option>
  <option value="">Palembang, Sumatra - Indonesia ( PLM )</option>
  <option value="">Palermo, Sicily - Italy ( PMO )</option>
  <option value="">Palm Springs, CAВ - United States ( PSP )</option>
  <option value="">Palma, Mallorca - Spain ( PMI )</option>
  <option value="">Palmas - Brazil ( PMW )</option>
  <option value="">Palmerston North - New Zealand ( PMR )</option>
  <option value="">Pamplona - Spain ( PNA )</option>
  <option value="">Panama City - Panama ( PTY )</option>
  <option value="">Panama City, FLВ - United States ( PFN )</option>
  <option value="">Papeete, Tahiti - French Polynesia ( PPT )</option>
  <option value="">Paphos - Cyprus ( PFO )</option>
  <option value="">Paraburdoo, W.A. - Australia ( PBO )</option>
  <option value="">Paramaribo - Suriname ( PBM )</option>
  <option value="">Paris - France ( CDG )</option>
  <option value="">Paris - France ( ORY )</option>
  <option value="">Paris - France ( PAR -All )</option>
  <option value="">Parkersburg, WVВ - United States ( PKB )</option>
  <option value="">Parkes, N.S.W. - Australia ( PKE )</option>
  <option value="">Pasco, WAВ - United States ( PSC )</option>
  <option value="">Pau - France ( PUF )</option>
  <option value="">Pellston, MIВ - United States ( PLN )</option>
  <option value="">Penang, Penang Island - Malaysia ( PEN )</option>
  <option value="">Pendleton, ORВ - United States ( PDT )</option>
  <option value="">Pensacola, FLВ - United States ( PNS )</option>
  <option value="">Penticton, BC - Canada ( YYF )</option>
  <option value="">Penticton, BCВ - CanadaВ ( YYF )</option>
  <option value="">Peoria, ILВ - United States ( PIA )</option>
  <option value="">Perpignan - France ( PGF )</option>
  <option value="">Perth, W.A. - Australia ( PER )</option>
  <option value="">Perugia - Italy ( PEG )</option>
  <option value="">Peshawar - Pakistan ( PEW )</option>
  <option value="">Petropavlovsk-Kamchatsky, Siberia - Russia ( PKC )</option>
  <option value="">Philadelphia, PAВ - United States ( PHL )</option>
  <option value="">Philipsburg - St. Maarten ( SXM )</option>
  <option value="">Phitsanulok - Thailand ( PHS )</option>
  <option value="">Phnom Penh - Cambodia ( PNH )</option>
  <option value="">Phoenix, AZВ - United States ( PHX )</option>
  <option value="">Phuket - Thailand ( HKT )</option>
  <option value="">Piedras Negras - Mexico ( PDS )</option>
  <option value="">Pierre, SDВ - United States ( PIR )</option>
  <option value="">Pinehurst, NCВ - United States ( SOP )</option>
  <option value="">Pisa - Italy ( PSA )</option>
  <option value="">Pittsburgh, PAВ - United States ( PIT )</option>
  <option value="">Placencia - Belize ( PLJ )</option>
  <option value="">Plattsburgh, NYВ - United States ( PLB )</option>
  <option value="">Pleiku - Vietnam ( PXU )</option>
  <option value="">Pocatello, IDВ - United States ( PIH )</option>
  <option value="">Pohnpei - Micronesia ( PNI )</option>
  <option value="">Pointe-A-Pitre, Grande-Terre - Guadeloupe ( PTP )</option>
  <option value="">Ponca City, OKВ - United States ( PNC )</option>
  <option value="">Ponta Delgada, Sao Miguel Island - Azores ( PDL )</option>
  <option value="">Port Hardy, BC - Canada ( YZT )</option>
  <option value="">Port Hardy, BC - CanadaВ ( YZT )</option>
  <option value="">Port Hedland, W.A. - Australia ( PHE )</option>
  <option value="">Port Lincoln, S.A. - Australia ( PLO )</option>
  <option value="">Port Macquarie, N.S.W. - Australia ( PQQ )</option>
  <option value="">Port Moresby - Papua-New Guinea ( POM )</option>
  <option value="">Port of Spain - Trinidad and Tobago ( POS )</option>
  <option value="">Port Vila, Efate Island - Vanuatu ( VLI )</option>
  <option value="">Port-au-Prince - Haiti ( PAP )</option>
  <option value="">Portland, MEВ - United States ( PWM )</option>
  <option value="">Portland, ORВ - United States ( PDX )</option>
  <option value="">Portland, Vic. - Australia ( PTJ )</option>
  <option value="">Porto - Portugal ( OPO )</option>
  <option value="">Porto Alegre - Brazil ( POA )</option>
  <option value="">Porto Santo - Madeira ( PXO )</option>
  <option value="">Portsmouth, NHВ - United States ( PSM )</option>
  <option value="">Powell River, BC - Canada ( YPW )</option>
  <option value="">Powell River, BCВ - CanadaВ ( YPW )</option>
  <option value="">Poznan - Poland ( POZ )</option>
  <option value="">Prague - Czech Republic ( PRG )</option>
  <option value="">Prescott, AZВ - United States ( PRC )</option>
  <option value="">Presque Isle, MEВ - United States ( PQI )</option>
  <option value="">Prince George, BC - Canada ( YXS )</option>
  <option value="">Prince George, BCВ - CanadaВ ( YXS )</option>
  <option value="">Prince Rupert, BC - Canada ( YPR )</option>
  <option value="">Prince Rupert, BCВ - CanadaВ ( YPR )</option>
  <option value="">Proserpine, Qld. - Australia ( PPP )</option>
  <option value="">Providence, RIВ - United States ( PVD )</option>
  <option value="">
    Providenciales Island - Turks and Caicos Islands ( PLS )
  </option>
  <option value="">Provincetown, MAВ - United States ( PVC )</option>
  <option value="">Pucon - Chile ( ZPC )</option>
  <option value="">Puebla - Mexico ( PBC )</option>
  <option value="">Pueblo, COВ - United States ( PUB )</option>
  <option value="">
    Puerto del Rosario, Fuerteventura Island - Canary Islands ( FUE )
  </option>
  <option value="">Puerto Escondido - Mexico ( PXM )</option>
  <option value="">Puerto Montt - Chile ( PMC )</option>
  <option value="">Puerto Plata - Dominican Republic ( POP )</option>
  <option value="">Puerto Princesa - Philippines ( PPS )</option>
  <option value="">Puerto Vallarta - Mexico ( PVR )</option>
  <option value="">Pullman, WAВ - United States ( PUW )</option>
  <option value="">Punta Arenas, Tierra del Fuego - Chile ( PUQ )</option>
  <option value="">Punta Cana - Dominican Republic ( PUJ )</option>
  <option value="">Punta Gorda - Belize ( PND )</option>
  <option value="">Puttaparthi - India ( PUT )</option>
  <option value="">Pyongyang - North Korea ( FNJ )</option>
  <option value="">Qingdao - China ( TAO )</option>
  <option value="">Quebec, PQ - Canada ( YQB )</option>
  <option value="">Quebec, PQВ - CanadaВ ( YQB )</option>
  <option value="">Queenstown - New Zealand ( ZQN )</option>
  <option value="">Queretaro - Mexico ( QRO )</option>
  <option value="">Quesnel, BC - Canada ( YQZ )</option>
  <option value="">Quesnel, BCВ - CanadaВ ( YQZ )</option>
  <option value="">Quimper - France ( UIP )</option>
  <option value="">Quincy, ILВ - United States ( UIN )</option>
  <option value="">Quito - Ecuador ( UIO )</option>
  <option value="">Rach Gia - Vietnam ( VKG )</option>
  <option value="">Raleigh, NCВ - United States ( RDU )</option>
  <option value="">Rangoon - Myanmar (Burma) ( RGN )</option>
  <option value="">Rankin Inlet, NWT - Canada ( YRT )</option>
  <option value="">Rankin Inlet, NWT - CanadaВ ( YRT )</option>
  <option value="">Ranong - Thailand ( UNN )</option>
  <option value="">Rapid City, SDВ - United States ( RAP )</option>
  <option value="">Recife - Brazil ( REC )</option>
  <option value="">Red Lake, ON - Canada ( YRL )</option>
  <option value="">Red Lake, ONВ - CanadaВ ( YRL )</option>
  <option value="">Redding, CAВ - United States ( RDD )</option>
  <option value="">Redmond, ORВ - United States ( RDM )</option>
  <option value="">Reggio di Calabria - Italy ( REG )</option>
  <option value="">Regina, SK - Canada ( YQR )</option>
  <option value="">Regina, SKВ - CanadaВ ( YQR )</option>
  <option value="">Rennes - France ( RNS )</option>
  <option value="">Reno, NVВ - United States ( RNO )</option>
  <option value="">Reykjavik - Iceland ( KEF )</option>
  <option value="">Reykjavik - Iceland ( REK - All Airports )</option>
  <option value="">Reykjavik - Iceland ( RKV )</option>
  <option value="">Reynosa - Mexico ( REX )</option>
  <option value="">Rhinelander, WI - United States ( RHI )</option>
  <option value="">Rhodes - Greece ( RHO )</option>
  <option value="">Richmond, VAВ - United States ( RIC )</option>
  <option value="">Riga - Latvia ( RIX )</option>
  <option value="">Rimini - Italy ( RMI )</option>
  <option value="">Rio de Janeiro - Brazil ( GIG )</option>
  <option value="">Rio de Janeiro - Brazil ( RIO - All Airports )</option>
  <option value="">Rio de Janeiro - Brazil ( SDU )</option>
  <option value="">Riverton, WYВ - United States ( RIW )</option>
  <option value="">Riyadh - Saudi Arabia ( RUH )</option>
  <option value="">Roanoke, VAВ - United States ( ROA )</option>
  <option value="">Roberval, PQ - Canada ( YRJ )</option>
  <option value="">Roberval, PQВ - CanadaВ ( YRJ )</option>
  <option value="">Rochester, MNВ - United States ( RST )</option>
  <option value="">Rochester, NYВ - United States ( ROC )</option>
  <option value="">Rock Sound - Bahamas ( RSD )</option>
  <option value="">Rock Springs, WYВ - United States ( RKS )</option>
  <option value="">Rockford, ILВ - United States ( RFD )</option>
  <option value="">Rockhampton, Qld. - Australia ( ROK )</option>
  <option value="">Rockland, MEВ - United States ( RKD )</option>
  <option value="">Rodez - France ( RDZ )</option>
  <option value="">Roma, Qld. - Australia ( RMA )</option>
  <option value="">Rome - Italy ( CIA )</option>
  <option value="">Rome - Italy (FCO-Leonardo Da Vinci ( FCO )</option>
  <option value="">Rome - Italy ( ROM-All )</option>
  <option value="">Ronne - Denmark ( RNN )</option>
  <option value="">Ronneby - Sweden ( RNB )</option>
  <option value="">Roseau - Dominica ( DOM )</option>
  <option value="">Rostov - Russia ( ROV )</option>
  <option value="">Roswell, NMВ - United States ( ROW )</option>
  <option value="">Rotorua - New Zealand ( ROT )</option>
  <option value="">Rotterdam - Netherlands ( RTM )</option>
  <option value="">Rouen - France ( URO )</option>
  <option value="">Rouyn-Noranda, PQ - Canada ( YUY )</option>
  <option value="">Rouyn-Noranda, PQВ - CanadaВ ( YUY )</option>
  <option value="">Rovaniemi - Finland ( RVN )</option>
  <option value="">Roxas City - Philippines ( RXS )</option>
  <option value="">Rutland, VTВ - United States ( RUT )</option>
  <option value="">Rzeszow - Poland ( RZE )</option>
  <option value="">Saba Island - Saba ( SAB )</option>
  <option value="">Sacramento, CAВ - United States ( SMF )</option>
  <option value="">Saga - Japan ( HSG )</option>
  <option value="">Saginaw, MIВ - United States ( MBS )</option>
  <option value="">Saint John, NB - Canada ( YSJ )</option>
  <option value="">Saint John, NBВ - CanadaВ ( YSJ )</option>
  <option value="">Saint-Denis - Reunion ( RUN )</option>
  <option value="">Saint-Pierre - Reunion ( ZSE )</option>
  <option value="">Saipan - Northern Mariana Islands ( SPN )</option>
  <option value="">Salina, KSВ - United States ( SLN )</option>
  <option value="">Salisbury, MDВ - United States ( SBY )</option>
  <option value="">Salt Lake City, UTВ - United States ( SLC )</option>
  <option value="">Saltillo - Mexico ( SLW )</option>
  <option value="">Salvador - Brazil ( SSA )</option>
  <option value="">Salzburg - Austria ( SZG )</option>
  <option value="">Samsun - Turkey ( SZF )</option>
  <option value="">San Andres - Colombia ( ADZ )</option>
  <option value="">San - Bahamas ( SAQ )</option>
  <option value="">San Angelo, TXВ - United States ( SJT )</option>
  <option value="">San Antonio, TXВ - United States ( SAT )</option>
  <option value="">San Carlos de Bariloche - Argentina ( BRC )</option>
  <option value="">San Diego, CAВ - United States ( SAN )</option>
  <option value="">San Francisco, CAВ - United States ( QSFВ -All )</option>
  <option value="">San Francisco, CAВ - United States ( SFO )</option>
  <option value="">San Jose - Costa Rica ( SJO )</option>
  <option value="">San Jose, CAВ - United States ( SJC )</option>
  <option value="">San Juan - Puerto Rico ( SJU )</option>
  <option value="">San Luis Obispo, CAВ - United States ( SBP )</option>
  <option value="">San Luis Potosi - Mexico ( SLP )</option>
  <option value="">San Salvador - El Salvador ( SAL )</option>
  <option value="">San Sebastian - Spain ( EAS )</option>
  <option value="">Sanaa - Yemen ( SAH )</option>
  <option value="">Sand Point, AKВ - United States ( SDP )</option>
  <option value="">Sandakan, Sabah - Malaysia ( SDK )</option>
  <option value="">Tiruchirappalli - India ( TRZ )</option>
  <option value="">Sandefjord - Norway ( TRF )</option>
  <option value="">
    Sandspit, Queen Charlotte Islands, BC - Canada ( YZP )
  </option>
  <option value="">
    Sandspit, Queen Charlotte Islands, BC - CanadaВ ( YZP )
  </option>
  <option value="">Santa Barbara, CAВ - United States ( SBA )</option>
  <option value="">Santa Cruz - Spain ( SPC )</option>
  <option value="">Santa Cruz de Tenerife - Canary Islands ( TFN )</option>
  <option value="">Santa Fe, NMВ - United States ( SAF )</option>
  <option value="">Santa Maria, CAВ - United States ( SMX )</option>
  <option value="">Santa Maria, Sal Island - Cape Verde ( SID )</option>
  <option value="">Santa Rosa - Argentina ( RSA )</option>
  <option value="">Santa Rosa, CAВ - United States ( STS )</option>
  <option value="">Santander - Spain ( SDR )</option>
  <option value="">Santiago - Chile ( SCL )</option>
  <option value="">Santiago - Dominican Republic ( STI )</option>
  <option value="">Santo Domingo - Dominican Republic ( SDQ )</option>
  <option value="">Sanya - China ( SYX )</option>
  <option value="">Sao Jose So Rio Preto - Brazil ( SJP )</option>
  <option value="">Sao Paulo - Brazil ( CGH )</option>
  <option value="">Sao Paulo - Brazil ( GRU )</option>
  <option value="">Sao Paulo - Brazil ( SAO - All Airports )</option>
  <option value="">Sapporo - Japan ( CTS )</option>
  <option value="">Sapporo - Japan ( OKD )</option>
  <option value="">Sarajevo - Bosnia and Herzegovina ( SJJ )</option>
  <option value="">Saranac Lake, NYВ - United States ( SLK )</option>
  <option value="">Sarasota, FLВ - United States ( SRQ )</option>
  <option value="">Sarnia, ON - Canada ( YZR )</option>
  <option value="">Sarnia, ONВ - CanadaВ ( YZR )</option>
  <option value="">Saskatoon, SK - Canada ( YXE )</option>
  <option value="">Saskatoon, SKВ - CanadaВ ( YXE )</option>
  <option value="">Sault Ste. Marie, MI - United States ( CIU )</option>
  <option value="">Sault Ste. Marie, ON - Canada ( YAM )</option>
  <option value="">Sault Ste. Marie, ON - CanadaВ ( YAM )</option>
  <option value="">Savannah, GAВ - United States ( SAV )</option>
  <option value="">Scottsbluff, NEВ - United States ( BFF )</option>
  <option value="">Seattle, WAВ - United States ( SEA )</option>
  <option value="">Semipalatinsk - Kazakhstan ( PLX )</option>
  <option value="">Seoul, Korea - Republic of ( GMP )</option>
  <option value="">Seoul, Korea - Republic of ( ICN )</option>
  <option value="">Sept-Iles, PQ - Canada ( YZV )</option>
  <option value="">Sept-Iles, PQ - CanadaВ ( YZV )</option>
  <option value="">Seville - Spain ( SVQ )</option>
  <option value="">Shanghai - China ( PVG )</option>
  <option value="">Shanghai - China ( SHA )</option>
  <option value="">Shannon - Ireland ( SNN )</option>
  <option value="">Shantou - China ( SWA )</option>
  <option value="">Sharjah - United Arab Emirates ( SHJ )</option>
  <option value="">Sharm El Sheikh - Egypt ( SSH )</option>
  <option value="">
    Shenandoah Valley Airport, VAВ - United States ( SHD )
  </option>
  <option value="">Shenyang - China ( SHE )</option>
  <option value="">Shenzhen - China ( SZX )</option>
  <option value="">Sheridan, WYВ - United States ( SHR )</option>
  <option value="">Shijiazhuang - China ( SJW )</option>
  <option value="">Shreveport, LAВ - United States ( SHV )</option>
  <option value="">Sibu, Sarawak - Malaysia ( SBW )</option>
  <option value="">Sidney, MTВ - United States ( SDY )</option>
  <option value="">Silver City, NMВ - United States ( SVC )</option>
  <option value="">Singapore - Singapore ( SIN )</option>
  <option value="">Sioux City, IAВ - United States ( SUX )</option>
  <option value="">Sioux Falls, SDВ - United States ( FSD )</option>
  <option value="">Sioux Lookout, ON - Canada ( YXL )</option>
  <option value="">Sioux Lookout, ON - CanadaВ ( YXL )</option>
  <option value="">Sitka, AKВ - United States ( SIT )</option>
  <option value="">Skagway, AKВ - United States ( SGY )</option>
  <option value="">Skelleftea - Sweden ( SFT )</option>
  <option value="">Skopje - Macedonia ( SKP )</option>
  <option value="">Smithers, BC - Canada ( YYD )</option>
  <option value="">Smithers, BC - CanadaВ ( YYD )</option>
  <option value="">Sofia - Bulgaria ( SOF )</option>
  <option value="">Sonderborg - Denmark ( SGD )</option>
  <option value="">Songpan Jiuzhai Huanglong - China ( JZH )</option>
  <option value="">South - Bahamas ( TZN )</option>
  <option value="">South Bend, INВ - United States ( SBN )</option>
  <option value="">Southampton - England ( SOU )</option>
  <option value="">Split - Croatia ( SPU )</option>
  <option value="">Spokane, WAВ - United States ( GEG )</option>
  <option value="">Springfield, ILВ - United States ( SPI )</option>
  <option value="">Springfield, MAВ - United States ( CEF )</option>
  <option value="">Springfield, MOВ - United States ( SGF )</option>
  <option value="">Springfield, VTВ - United States ( VSF )</option>
  <option value="">St. Cloud, MNВ - United States ( STC )</option>
  <option value="">St. George, UTВ - United States ( SGU )</option>
  <option value="">St. George's - Grenada ( GND )</option>
  <option value="">St. John's - Antigua ( ANU )</option>
  <option value="">St. John's, NF - Canada ( YYT )</option>
  <option value="">St. John's, NFВ - CanadaВ ( YYT )</option>
  <option value="">St. Louis, MOВ - United States ( STL )</option>
  <option value="">St. Petersburg - Russia ( LED )</option>
  <option value="">St. Petersburg, FLВ - United States ( PIE )</option>
  <option value="">State College, PAВ - United States ( SCE )</option>
  <option value="">Stavanger - Norway ( SVG )</option>
  <option value="">Steamboat Springs, COВ - United States ( SBS )</option>
  <option value="">Stella Maris, Long Island - Bahamas ( SML )</option>
  <option value="">Stockholm - Sweden ( ARN )</option>
  <option value="">Stockholm - Sweden ( BMA )</option>
  <option value="">Stockholm - Sweden ( STO-All )</option>
  <option value="">Stornoway, Isle of Lewis - Scotland ( SYY )</option>
  <option value="">Storuman - Sweden ( SQO )</option>
  <option value="">Strasbourg - France ( SXB )</option>
  <option value="">Stuttgart - Germany ( STR )</option>
  <option value="">Subic Bay - Philippines ( SFS )</option>
  <option value="">Sudbury, ON - Canada ( YSB )</option>
  <option value="">Sudbury, ONВ - CanadaВ ( YSB )</option>
  <option value="">Sukhothai - Thailand ( THS )</option>
  <option value="">Sun Valley, IDВ - United States ( SUN )</option>
  <option value="">Sundsvall - Sweden ( SDL )</option>
  <option value="">Surabaya, Java - Indonesia ( SUB )</option>
  <option value="">Surat Thani - Thailand ( URT )</option>
  <option value="">Suva - Fiji ( SUV )</option>
  <option value="">Sydney, Cape Breton Island, NS - Canada ( YQY )</option>
  <option value="">Sydney, Cape Breton Island, NS - CanadaВ ( YQY )</option>
  <option value="">Sydney, N.S.W. - Australia ( SYD )</option>
  <option value="">Syracuse, NYВ - United States ( SYR )</option>
  <option value="">Szczecin - Poland ( SZZ )</option>
  <option value="">Taba - Egypt ( TCP )</option>
  <option value="">Tabriz - Iran ( TBZ )</option>
  <option value="">Tacloban - Philippines ( TAC )</option>
  <option value="">Taegu - South Korea ( TAE )</option>
  <option value="">Tagbilaran - Philippines ( TAG )</option>
  <option value="">Taichung - Taiwan ( RMQ )</option>
  <option value="">Taipei - Taiwan ( TPE )</option>
  <option value="">Taipei - Taiwan ( TSA )</option>
  <option value="">Taiyuan - China ( TYN )</option>
  <option value="">Takamatsu - Japan ( TAK )</option>
  <option value="">Tallahassee, FLВ - United States ( TLH )</option>
  <option value="">Lampung - Indonesia ( TKG )</option>
  <option value="">Tallinn - Estonia ( TLL )</option>
  <option value="">Tampa, FLВ - United States ( TPA )</option>
  <option value="">Tampere - Finland ( TMP )</option>
  <option value="">Tampico - Mexico ( TAM )</option>
  <option value="">Tamworth, N.S.W. - Australia ( TMW )</option>
  <option value="">Tangier - Morocco ( TNG )</option>
  <option value="">Tapachula - Mexico ( TAP )</option>
  <option value="">Tashkent - Uzbekistan ( TAS )</option>
  <option value="">Taupo - New Zealand ( TUO )</option>
  <option value="">Tauranga - New Zealand ( TRG )</option>
  <option value="">Tawau, Sabah - Malaysia ( TWU )</option>
  <option value="">Tbilisi - Georgia ( TBS )</option>
  <option value="">Teesside - England ( MME )</option>
  <option value="">Tegucigalpa - Honduras ( TGU )</option>
  <option value="">Tehran - Iran ( THR )</option>
  <option value="">Tel Aviv - Israel ( TLV )</option>
  <option value="">Telluride, CO - United States ( TEX )</option>
  <option value="">Temuco - Chile ( ZCO )</option>
  <option value="">
    Tenerife Island - Canary Islands ( TCI - All Airports )
  </option>
  <option value="">Tenerife Island - Canary Islands ( TFS )</option>
  <option value="">
    Tenerife Island - Canary Islands ( TVI - All Airports )
  </option>
  <option value="">Tepic - Mexico ( TPQ )</option>
  <option value="">Termez - Uzbekistan ( TMJ )</option>
  <option value="">Terrace, BC - Canada ( YXT )</option>
  <option value="">Terrace, BC - CanadaВ ( YXT )</option>
  <option value="">Texarkana, ARВ - United States ( TXK )</option>
  <option value="">The Valley - Anguilla ( AXA )</option>
  <option value="">Thessaloniki - Greece ( SKG )</option>
  <option value="">Thief River Falls, MNВ - United States ( TVF )</option>
  <option value="">Thira, Santorini Island - Greece ( JTR )</option>
  <option value="">Thompson, MB - Canada ( YTH )</option>
  <option value="">Thompson, MBВ - CanadaВ ( YTH )</option>
  <option value="">Thunder Bay, ON - Canada ( YQT )</option>
  <option value="">Thunder Bay, ONВ - CanadaВ ( YQT )</option>
  <option value="">Tianjin - China ( TSN )</option>
  <option value="">Tijuana - Mexico ( TIJ )</option>
  <option value="">Timaru - New Zealand ( TIU )</option>
  <option value="">Timmins, ON - Canada ( YTS )</option>
  <option value="">Timmins, ONВ - CanadaВ ( YTS )</option>
  <option value="">Tirana - Albania ( TIA )</option>
  <option value="">Tobago - Trinidad and Tobago ( TAB )</option>
  <option value="">Toksook Bay, AKВ - United States ( OOK )</option>
  <option value="">Tokyo - Japan ( HND )</option>
  <option value="">Tokyo - Japan ( NRT )</option>
  <option value="">Tokyo - Japan ( TYO - All Airports )</option>
  <option value="">Toledo, OHВ - United States ( TOL )</option>
  <option value="">Toluca - Mexico ( TLC )</option>
  <option value="">Tongren - China ( TEN )</option>
  <option value="">Topeka, KSВ - United States ( TOP )</option>
  <option value="">Toronto, ON - Canada ( YTO - All Airports )</option>
  <option value="">Toronto, ON - Canada ( YTZ )</option>
  <option value="">Toronto, ON - Canada ( YYZ )</option>
  <option value="">Toronto, ONВ - CanadaВ ( YTOВ -AllВ )</option>
  <option value="">Toronto, ONВ - CanadaВ ( YTZ )</option>
  <option value="">Toronto, ONВ - CanadaВ ( YYZ )</option>
  <option value="">Torreon - Mexico ( TRC )</option>
  <option value="">Toulon - France ( TLN )</option>
  <option value="">Toulouse - France ( TLS )</option>
  <option value="">Townsville, Qld. - Australia ( TSV )</option>
  <option value="">Trang - Thailand ( TST )</option>
  <option value="">Trat - Thailand ( TDX )</option>
  <option value="">Traverse City, MIВ - United States ( TVC )</option>
  <option value="">Treasure Cay, Abaco Island - Bahamas ( TCB )</option>
  <option value="">Trenton, NJВ - United States ( TTN )</option>
  <option value="">Tri-City Airport, TNВ - United States ( TRI )</option>
  <option value="">Trieste - Italy ( TRS )</option>
  <option value="">Tripoli - Libya ( TIP )</option>
  <option value="">Tromso - Norway ( TOS )</option>
  <option value="">Trondheim - Norway ( TRD )</option>
  <option value="">Truk - Micronesia ( TKK )</option>
  <option value="">Tucson, AZВ - United States ( TUS )</option>
  <option value="">Tulsa, OKВ - United States ( TUL )</option>
  <option value="">Tunis - Tunisia ( TUN )</option>
  <option value="">Tupelo, MSВ - United States ( TUP )</option>
  <option value="">Turin - Italy ( TRN )</option>
  <option value="">Turku - Finland ( TKU )</option>
  <option value="">Tuxtla Gutierrez - Mexico ( TGZ )</option>
  <option value="">Twin Falls, IDВ - United States ( TWF )</option>
  <option value="">Tyler, TXВ - United States ( TYR )</option>
  <option value="">Ubon Ratchathani - Thailand ( UBP )</option>
  <option value="">Udon Thani - Thailand ( UTH )</option>
  <option value="">Ujung Pandang, Sulawesi - Indonesia ( UPG )</option>
  <option value="">Ulan Bator - Mongolia ( ULN )</option>
  <option value="">Umea - Sweden ( UME )</option>
  <option value="">Una - Brazil ( UNA )</option>
  <option value="">Unalakleet, AKВ - United States ( UNK )</option>
  <option value="">Urumqi, Sinkiang - China ( URC )</option>
  <option value="">Ushuaia, Tierra del Fuego - Argentina ( USH )</option>
  <option value="">Ust Kamenogorsk - Kazakhstan ( UKK )</option>
  <option value="">Utapao - Thailand ( UTP )</option>
  <option value="">Vaasa - Finland ( VAA )</option>
  <option value="">Vail, COВ - United States ( EGE )</option>
  <option value="">Val-d'Or, PQ - Canada ( YVO )</option>
  <option value="">Val-d'Or, PQ - CanadaВ ( YVO )</option>
  <option value="">Valdez, AKВ - United States ( VDZ )</option>
  <option value="">Valdivia - Chile ( ZAL )</option>
  <option value="">Valdosta, GAВ - United States ( VLD )</option>
  <option value="">Valencia - Spain ( VLC )</option>
  <option value="">Valladolid - Spain ( VLL )</option>
  <option value="">Valletta - Malta ( MLA )</option>
  <option value="">Vancouver, BC - Canada ( YVR )</option>
  <option value="">Vancouver, BCВ - CanadaВ ( YVR )</option>
  <option value="">Varanasi - India ( VNS )</option>
  <option value="">Bagdogra - India ( IXB )</option>
  <option value="">Varna - Bulgaria ( VAR )</option>
  <option value="">Vasteras - Sweden ( VST )</option>
  <option value="">Vaxjo - Sweden ( VXO )</option>
  <option value="">Venice - Italy ( VCE )</option>
  <option value="">Veracruz - Mexico ( VER )</option>
  <option value="">Verona - Italy ( VRN )</option>
  <option value="">Victoria, BC - Canada ( YYJ )</option>
  <option value="">Victoria, BCВ - CanadaВ ( YYJ )</option>
  <option value="">Victoria, Mahe Island - Seychelles ( SEZ )</option>
  <option value="">Victoria, TXВ - United States ( VCT )</option>
  <option value="">Vienna - Austria ( VIE )</option>
  <option value="">Vientiane - Laos ( VTE )</option>
  <option value="">Vieques - Puerto Rico ( VQS )</option>
  <option value="">Vieux Fort - St. Lucia ( UVF )</option>
  <option value="">Vigo - Spain ( VGO )</option>
  <option value="">Vilhelmina - Sweden ( VHM )</option>
  <option value="">Villahermosa - Mexico ( VSA )</option>
  <option value="">Vilnius - Lithuania ( VNO )</option>
  <option value="">Vinh City - Vietnam ( VII )</option>
  <option value="">Visalia, CAВ - United States ( VIS )</option>
  <option value="">Visby - Sweden ( VBY )</option>
  <option value="">Vitoria - Spain ( VIT )</option>
  <option value="">Vladivostok, Siberia - Russia ( VVO )</option>
  <option value="">Volgograd - Russia ( VOG )</option>
  <option value="">Wabush, Labrador, NF - Canada ( YWK )</option>
  <option value="">Wabush, Labrador, NFВ - CanadaВ ( YWK )</option>
  <option value="">Waco, TXВ - United States ( ACT )</option>
  <option value="">Wagga-Wagga, N.S.W. - Australia ( WGA )</option>
  <option value="">Wajima - Japan ( NTQ )</option>
  <option value="">Walla Walla, WAВ - United States ( ALW )</option>
  <option value="">Wanganui - New Zealand ( WAG )</option>
  <option value="">Warri - Nigeria ( QRW )</option>
  <option value="">Warsaw - Poland ( WAW )</option>
  <option value="">Washington DCВ - United States ( DCA )</option>
  <option value="">Washington DCВ - United States ( IAD )</option>
  <option value="">Waterloo, IAВ - United States ( ALO )</option>
  <option value="">Windhoek - Namibia ( WDH )</option>
  <option value="">Watertown, NYВ - United States ( ART )</option>
  <option value="">Watertown, SDВ - United States ( ATY )</option>
  <option value="">Wausau, WIВ - United States ( CWA )</option>
  <option value="">Weipa, Qld. - Australia ( WEI )</option>
  <option value="">Wellington - New Zealand ( WLG )</option>
  <option value="">Wenatchee, WAВ - United States ( EAT )</option>
  <option value="">West Palm Beach, FLВ - United States ( PBI )</option>
  <option value="">West Yellowstone, MT - United States ( WYS )</option>
  <option value="">Westport - New Zealand ( WSZ )</option>
  <option value="">Whakatane - New Zealand ( WHK )</option>
  <option value="">Whangarei - New Zealand ( WRE )</option>
  <option value="">White Plains, NYВ - United States ( HPN )</option>
  <option value="">Whitehorse, YT - Canada ( YXY )</option>
  <option value="">Whitehorse, YTВ - CanadaВ ( YXY )</option>
  <option value="">Whyalla, S.A. - Australia ( WYA )</option>
  <option value="">Wichita Falls, TXВ - United States ( SPS )</option>
  <option value="">Wichita, KSВ - United States ( ICT )</option>
  <option value="">Wick - Scotland ( WIC )</option>
  <option value="">Wilkes-Barre, PAВ - United States ( AVP )</option>
  <option value="">Willemstad - Curacao ( CUR )</option>
  <option value="">Williams Lake, BC - Canada ( YWL )</option>
  <option value="">Williams Lake, BC - CanadaВ ( YWL )</option>
  <option value="">Williamsport, PAВ - United States ( IPT )</option>
  <option value="">Williston, NDВ - United States ( ISN )</option>
  <option value="">Wilmington, DEВ - United States ( ILG )</option>
  <option value="">Wilmington, NCВ - United States ( ILM )</option>
  <option value="">Windsor, ON - Canada ( YQG )</option>
  <option value="">Windsor, ONВ - CanadaВ ( YQG )</option>
  <option value="">Winnipeg, MB - Canada ( YWG )</option>
  <option value="">Winnipeg, MBВ - CanadaВ ( YWG )</option>
  <option value="">Wolf Point, MT - United States ( OLF )</option>
  <option value="">Worland, WYВ - United States ( WRL )</option>
  <option value="">Wrangell, AKВ - United States ( WRG )</option>
  <option value="">Wroclaw - Poland ( WRO )</option>
  <option value="">Wuhan - China ( WUH )</option>
  <option value="">Xi'an - China ( XIY )</option>
  <option value="">Xiamen - China ( XMN )</option>
  <option value="">Xichang - China ( XIC )</option>
  <option value="">Yakima, WAВ - United States ( YKM )</option>
  <option value="">Yakutat, AKВ - United States ( YAK )</option>
  <option value="">Yamagata - Japan ( GAJ )</option>
  <option value="">Yangyang, Korea - Republic of ( YNY )</option>
  <option value="">Yanji - China ( YNJ )</option>
  <option value="">Yantai - China ( YNT )</option>
  <option value="">Yaounde - Cameroon ( NSI )</option>
  <option value="">Yaounde - Cameroon ( YAO )</option>
  <option value="">Yap - Micronesia ( YAP )</option>
  <option value="">Yellowknife, NWT - Canada ( YZF )</option>
  <option value="">Yellowknife, NWT - CanadaВ ( YZF )</option>
  <option value="">Yerevan - Armenia ( EVN )</option>
  <option value="">Yogyakarta, Java - Indonesia ( JOG )</option>
  <option value="">Yuma, AZВ - United States ( YUM )</option>
  <option value="">Zacatecas - Mexico ( ZCL )</option>
  <option value="">Zadar - Croatia ( ZAD )</option>
  <option value="">Zagreb - Croatia ( ZAG )</option>
  <option value="">Zamboanga - Philippines ( ZAM )</option>
  <option value="">Zanzibar - Tanzania ( ZNZ )</option>
  <option value="">Zaragoza - Spain ( ZAZ )</option>
  <option value="">Zhengzhou - China ( CGO )</option>
  <option value="">Zhoushan - China ( HSN )</option>
  <option value="">Goiania - Brazil ( GYN )</option>
  <option value="">Londrina - Brazil ( LDB )</option>
  <option value="">Thiruvananthapuram - India ( TRV )</option>
  <option value="">Zurich - Switzerland ( ZRH )</option>
</select>;
